var pieces = [["Asturias", "e minor", "Albeniz", 6, 5, "Contemporary", []],
["Concerto No 7 BWV 1058 Mvt 1", "g minor", "Bach", 4, 5, "Baroque", []],
["Invention No 8", "F Major", "Bach", 1, 5, "Baroque", []],
["Prelude and Fugue BWV 881", "f minor", "Bach", 6, 5, "Baroque", []],
["Adagio for Strings", "bb minor", "Barber", 8, 5, "Contemporary", ["dark"]],
["Hungarian Pictures", "f# minor", "Bartok", 11, 3, "Contemporary", ["impressions"]],
["Romanian Folk Dances", "a minor", "Bartok", 6, 5, "Contemporary", []],
["Piano Concerto No 1 Mvt 1", "C Major", "Beethoven", 19, 5, "Classical", []],
["Piano Concerto No 1 Mvt 2", "Ab Major", "Beethoven", 11, 3, "Classical", []],
["Piano Concerto No 1 Mvt 3", "C Major", "Beethoven", 9, 5, "Classical", []],
["Piano Concerto No 3 Mvt 1", "c minor", "Beethoven", 17, 5, "Classical", []],
["Piano Concerto No 3 Mvt 2", "E Major", "Beethoven", 11, 5, "Classical", []],
["Piano Concerto No 3 Mvt 3", "c minor", "Beethoven", 9, 5, "Classical", []],
["Piano Concerto No 4 Mvt 1", "G Major", "Beethoven", 20, 3, "Classical", ["stamina"]],
["Piano Concerto No 4 Mvt 2", "e minor", "Beethoven", 6, 4, "Classical", []],
["Piano Concerto No 4 Mvt 3", "G Major", "Beethoven", 10, 3, "Classical", ["stamina"]],
["Piano Concerto No 5 Mvt 1", "Eb Major", "Beethoven", 21, 4, "Classical", []],
["Piano Concerto No 5 Mvt 2", "B Major", "Beethoven", 9, 3,  "Classical", ["uplifting", "tender"]],
["Piano Concerto No 5 Mvt 3", "Eb Major", "Beethoven", 12, 4, "Classical", []],
["Rage over a Lost Penny", "G Major", "Beethoven", 6, 4, "Classical", ["stamina"]],
["Sonata No 1 Mvt 14", "f minor", "Beethoven", 7, 3, "Classical", ["stamina"]],
["Sonata No 2 Mvt 1", "A Major", "Beethoven", 5, 4, "Classical", []],
["Sonata No 3 Mvt 1", "C Major", "Beethoven", 10, 4, "Classical", []],
["Sonata No 4 Mvt 134", "Eb Major", "Beethoven", 18, 4, "Classical", []],
["Sonata No 5 Mvt 1", "c minor", "Beethoven", 4, 5, "Classical", []],
["Sonata No 6 Mvt 13", "F Major", "Beethoven", 6, 4, "Classical", []],
["Sonata No 7 Mvt 1", "D Major", "Beethoven", 7, 3, "Classical", ["stamina"]],
["Sonata No 8", "c minor", "Beethoven", 20, 3, "Classical", []],
["Sonata No 9 Mvt 1", "E Major", "Beethoven", 5, 4, "Classical", ["stamina"]],
["Sonata No 10 Mvt 12", "G Major", "Beethoven", 11, 4, "Classical", []],
["Sonata No 11 Mvt 14", "Bb Major", "Beethoven", 15, 3, "Classical", []],
["Sonata No 12 Mvt 3", "ab minor", "Beethoven", 6, 4, "Classical", ["dark"]],
["Sonata No 13 Mvt 24", "Eb Major", "Beethoven", 8, 4, "Classical", []],
["Sonata No 14", "c# minor", "Beethoven", 15, 3, "Classical", ["dark"]],
["Sonata No 15 Mvt 134", "D Major", "Beethoven", 19, 4, "Classical", ["sleepy"]],
["Sonata No 16 Mvt 1", "G Major", "Beethoven", 7, 5, "Classical", []],
["Sonata No 17", "d minor", "Beethoven", 23, 3, "Classical", ["dark"]],
["Sonata No 18 Mvt 14", "Eb Major", "Beethoven", 10, 4, "Classical", ["stamina"]],
["Sonata No 19", "g minor", "Beethoven", 9, 5, "Classical", []],
["Sonata No 20", "G Major", "Beethoven", 8, 5, "Classical", []],
["Sonata No 21 Mvt 13", "C Major", "Beethoven", 18, 3, "Classical", []],
["Sonata No 22", "F Major", "Beethoven", 12, 4, "Classical", []],
["Sonata No 23", "f minor", "Beethoven", 26, 4, "Classical", []],
["Sonata No 24", "F# Major", "Beethoven", 10, 4, "Classical", []],
["Sonata No 25", "G Major", "Beethoven", 12, 4, "Classical", []],
["Sonata No 26 Mvt 13", "Eb Major", "Beethoven", 13, 4, "Classical", []],
["Sonata No 27", "e minor", "Beethoven", 14, 3, "Classical", []],
["Sonata No 28", "A Major", "Beethoven", 21, 2, "Romantic", ["legendary", "uplifting"]],
["Sonata No 29 Mvt 12", "Bb Major", "Beethoven", 11, 4, "Romantic", ["legendary"]],
["Sonata No 30", "E Major", "Beethoven", 19, 2, "Romantic", ["legendary"]],
["Sonata No 31", "Ab Major", "Beethoven", 20, 1, "Romantic", ["legendary", "tender"]],
["Sonata No 32", "c minor", "Beethoven", 30, 2, "Romantic", ["legendary", "experimental"]],
["Symphony No 3 Mvt 1", "Eb Major", "Beethoven", 15, 5, "Classical", []],
["Symphony No 5 Mvt 1", "c minor", "Beethoven", 8, 4, "Classical", []],
["Symphony No 5 Mvt 2", "Ab Major", "Beethoven", 10, 4, "Classical", []],
["Symphony No 5 Mvt 3", "c minor", "Beethoven", 6, 4, "Classical", []],
["Symphony No 5 Mvt 4", "C Major", "Beethoven", 9, 4, "Classical", []],
["Symphony No 7 Mvt 1", "A Major", "Beethoven", 13, 4, "Classical", []],
["Symphony No 7 Mvt 2", "a minor", "Beethoven", 9, 4, "Classical", []],
["Symphony No 7 Mvt 3", "F Major", "Beethoven", 9, 4, "Classical", ["stamina"]],
["Symphony No 7 Mvt 4", "A Major", "Beethoven", 7, 4, "Classical", ["stamina"]],
["Symphony No 9 Mvt 1", "d minor", "Beethoven", 18, 5, "Classical", []],
["Symphony No 9 Mvt 2", "D Major", "Beethoven", 12, 5, "Classical", []],
["Symphony No 9 Mvt 3", "Bb Major", "Beethoven", 18, 5, "Classical", []],
["Symphony No 9 Mvt 4", "D Major", "Beethoven", 8, 5, "Classical", ["troll"]],
["Carmen Prelude", "A Major", "Bizet", 3, 2, "Romantic", []],
["Habanera", "F Major", "Bizet", 3, 4, "Romantic", []],
["Toreador Song", "F Major", "Bizet", 3, 5, "Romantic", []],
["Capriccio Op 116 No 3", "g minor", "Brahms", 3, 5, "Romantic", ["stamina"]],
["Hungarian Dance No 5", "g minor", "Brahms", 4, 5, "Romantic", []],
["Lullaby Op 49 No 4", "Eb Major", "Brahms", 3, 5, "Romantic", ["sleepy"]],
["Piano Concerto No 1 Mvt 1", "d minor", "Brahms", 25, 4, "Romantic", []],
["Piano Concerto No 1 Mvt 2", "D Major", "Brahms", 15, 4, "Romantic", []],
["Piano Concerto No 1 Mvt 3", "d minor", "Brahms", 13, 4, "Romantic", []],
["Piano Concerto No 2 Mvt 1", "Bb Major", "Brahms", 19, 3, "Romantic", ["legendary"]],
["Piano Concerto No 2 Mvt 2", "d minor", "Brahms", 10, 3, "Romantic", ["dark"]],
["Piano Concerto No 2 Mvt 3", "Bb Major", "Brahms", 15, 3, "Romantic", []],
["Piano Concerto No 2 Mvt 4", "Bb Major", "Brahms", 10, 4, "Romantic", []],
["Rhapsody Op 79 No 1", "b minor", "Brahms", 9, 2, "Romantic", ["stamina"]],
["Rhapsody Op 79 No 2", "g minor", "Brahms", 7, 3, "Romantic", ["dark"]],
["Variations on a Theme by Paganini Op 35", "a minor", "Brahms", 24, 4, "Romantic", []],
["Andante Spianato Op 22 No 1", "G Major", "Chopin", 5, 4, "Romantic", ["uplifting", "sleepy"]],
["Ballade No 1", "g minor", "Chopin", 10, 4, "Romantic", []],
["Ballade No 2", "F Major", "Chopin", 8, 3, "Romantic", ["legendary"]],
["Ballade No 3", "Ab Major", "Chopin", 7, 1, "Romantic", ["legendary"]],
["Ballade No 4", "f minor", "Chopin", 12, 4, "Romantic", []],
["Barcarolle Op 60", "F# Major", "Chopin", 9, 4, "Romantic", []],
["Berceuse Op 57", "Db Major", "Chopin", 5, 3, "Romantic", ["tender"]],
["Etude Op 10 No 1", "C Major", "Chopin", 2, 5, "Romantic", []],
["Etude Op 10 No 2", "a minor", "Chopin", 2, 5, "Romantic", []],
["Etude Op 10 No 3", "E Major", "Chopin", 5, 5, "Romantic", []],
["Etude Op 10 No 4", "c# minor", "Chopin", 2, 5, "Romantic", []],
["Etude Op 10 No 5", "Gb Major", "Chopin", 2, 5, "Romantic", []],
["Etude Op 10 No 6", "eb minor", "Chopin", 5, 5, "Romantic", []],
["Etude Op 10 No 7", "C Major", "Chopin", 2, 5, "Romantic", []],
["Etude Op 10 No 8", "F Major", "Chopin", 3, 5, "Romantic", []],
["Etude Op 10 No 9", "f minor", "Chopin", 3, 4, "Romantic", []],
["Etude Op 10 No 10", "Ab Major", "Chopin", 3, 5, "Romantic", []],
["Etude Op 10 No 11", "Eb Major", "Chopin", 3, 5, "Romantic", []],
["Etude Op 10 No 12", "c minor", "Chopin", 3, 5, "Romantic", []],
["Etude Op 25 No 1", "Ab Major", "Chopin", 4, 2, "Romantic", ["sleepy"]],
["Etude Op 25 No 2", "f minor", "Chopin", 2, 5, "Romantic", []],
["Etude Op 25 No 3", "F Major", "Chopin", 2, 5, "Romantic", []],
["Etude Op 25 No 4", "a minor", "Chopin", 2, 5, "Romantic", []],
["Etude Op 25 No 5", "e minor", "Chopin", 4, 5, "Romantic", []],
["Etude Op 25 No 6", "g# minor", "Chopin", 3, 5, "Romantic", []],
["Etude Op 25 No 7", "c# minor", "Chopin", 6, 5, "Romantic", []],
["Etude Op 25 No 8", "Db Major", "Chopin", 2, 5, "Romantic", []],
["Etude Op 25 No 9", "Gb Major", "Chopin", 5, 5, "Romantic", ["stamina"]],
["Etude Op 25 No 10", "b minor", "Chopin", 5, 5, "Romantic", []],
["Etude Op 25 No 11", "a minor", "Chopin", 4, 4, "Romantic", ["dark"]],
["Etude Op 25 No 12", "c minor", "Chopin", 3, 5, "Romantic", []],
["Fantaisie Op 49", "f minor", "Chopin", 12, 1, "Romantic", ["legendary"]],
["Funeral March Op 72 No 2", "c minor", "Chopin", 6, 5, "Romantic", []],
["Grande polonaise brillante Op 22 No 2", "Eb Major", "Chopin", 10, 4, "Romantic", []],
["Impromptu No 1 Op 29", "Ab Major", "Chopin", 5, 4, "Romantic", []],
["Impromptu No 2 Op 36", "F# Major", "Chopin", 6, 5, "Romantic", []],
["Impromptu No 3 Op 51", "Gb Major", "Chopin", 6, 5, "Romantic", []],
["Impromptu No 4 Op 66", "c# minor", "Chopin", 5, 4, "Romantic", []],
["Mazurka Op 59 No 3", "f# minor", "Chopin", 4, 5, "Romantic", []],
["Mazurka Op 67 No 4", "a minor", "Chopin", 4, 5, "Romantic", []],
["Nocturne No 20 Op Posth", "c# minor", "Chopin", 4, 4, "Romantic", []],
["Nocturne No 21 Op Posth", "c minor", "Chopin", 4, 5, "Romantic", []],
["Nocturne Op 9 No 1", "bb minor", "Chopin", 6, 4, "Romantic", ["sleepy"]],
["Nocturne Op 9 No 2", "Eb Major", "Chopin", 5, 4, "Romantic", ["sleepy"]],
["Nocturne Op 9 No 3", "B Major", "Chopin", 7, 5, "Romantic", []],
["Nocturne Op 15 No 1", "F Major", "Chopin", 5, 3, "Romantic", ["sleepy"]],
["Nocturne Op 15 No 2", "F# Major", "Chopin", 4, 4, "Romantic", ["sleepy"]],
["Nocturne Op 15 No 3", "g minor", "Chopin", 5, 5, "Romantic", []],
["Nocturne Op 27 No 1", "c# minor", "Chopin", 6, 4, "Romantic", []],
["Nocturne Op 27 No 2", "Db Major", "Chopin", 8, 4, "Romantic", ["sleepy"]],
["Nocturne Op 32 No 1", "B Major", "Chopin", 6, 4, "Romantic", ["sleepy"]],
["Nocturne Op 32 No 2", "Ab Major", "Chopin", 6, 4, "Romantic", []],
["Nocturne Op 37 No 1", "g minor", "Chopin", 7, 5, "Romantic", []],
["Nocturne Op 37 No 2", "G Major", "Chopin", 6, 3, "Romantic", ["sleepy"]],
["Nocturne Op 48 No 1", "c minor", "Chopin", 7, 3, "Romantic", ["sad"]],
["Nocturne Op 48 No 2", "f# minor", "Chopin", 7, 5, "Romantic", []],
["Nocturne Op 55 No 1", "f minor", "Chopin", 5, 4, "Romantic", []],
["Nocturne Op 55 No 2", "Eb Major", "Chopin", 5, 5, "Romantic", []],
["Nocturne Op 62 No 1", "B Major", "Chopin", 8, 5, "Romantic", []],
["Nocturne Op 62 No 2", "E Major", "Chopin", 6, 5, "Romantic", []],
["Nocturne Op 72 No 1", "e minor", "Chopin", 5, 5, "Romantic", []],
["Piano Concerto No 1 Op 11 Mvt 1", "e minor", "Chopin", 21, 1, "Romantic", ["legendary"]],
["Piano Concerto No 1 Op 11 Mvt 2", "E Major", "Chopin", 10, 1, "Romantic", ["uplifting"]],
["Piano Concerto No 1 Op 11 Mvt 3", "E Major", "Chopin", 10, 1, "Romantic", ["stamina"]],
["Piano Concerto No 2 Op 21 Mvt 1", "f minor", "Chopin", 16, 3, "Romantic", ["legendary"]],
["Piano Concerto No 2 Op 21 Mvt 2", "Ab Major", "Chopin", 12, 4, "Romantic", ["tender"]],
["Piano Concerto No 2 Op 21 Mvt 3", "f minor", "Chopin", 10, 2, "Romantic", []],
["Polonaise Fantaisie Op 61", "Ab Major", "Chopin", 14, 4, "Romantic", ["experimental"]],
["Polonaise Op 26 No 1", "c# minor", "Chopin", 8, 4, "Romantic", ["dark"]],
["Polonaise Op 26 No 2", "eb minor", "Chopin", 8, 3, "Romantic", []],
["Polonaise Op 40 No 1", "A Major", "Chopin", 5, 3, "Romantic", ["stamina"]],
["Polonaise Op 40 No 2", "c minor", "Chopin", 8, 5, "Romantic", []],
["Polonaise Op 44", "f# minor", "Chopin", 11, 4, "Romantic", ["dark", "stamina"]],
["Polonaise Op 53", "Ab Major", "Chopin", 7, 3, "Romantic", ["stamina"]],
["Polonaise Op 71 No 1", "d minor", "Chopin", 6, 5, "Romantic", []],
["Polonaise Op 71 No 2", "Bb Major", "Chopin", 7, 4, "Romantic", []],
["Polonaise Op 71 No 3", "f minor", "Chopin", 8, 5, "Romantic", []],
["Prelude Op 28 No 1", "C Major", "Chopin", 1, 4, "Romantic", []],
["Prelude Op 28 No 11", "B Major", "Chopin", 1, 5, "Romantic", []],
["Prelude Op 28 No 15", "Db Major", "Chopin", 6, 2, "Romantic", ["tender", "sleepy", "zen"]],
["Prelude Op 28 No 16", "bb minor", "Chopin", 2, 5, "Romantic", []],
["Prelude Op 28 No 17", "Ab Major", "Chopin", 4, 4, "Romantic", ["sleepy"]],
["Prelude Op 28 No 19", "Eb Major", "Chopin", 2, 5, "Romantic", []],
["Prelude Op 28 No 24", "d minor", "Chopin", 3, 5, "Romantic", []],
["Scherzo No 1 Op 20", "b minor", "Chopin", 10, 3, "Romantic", ["experimental"]],
["Scherzo No 2 Op 31", "bb minor", "Chopin", 9, 3, "Romantic", []],
["Scherzo No 3 Op 39", "C# Major", "Chopin", 8, 3, "Romantic", ["experimental"]],
["Scherzo No 4 Op 54", "E Major", "Chopin", 11, 3, "Romantic", ["experimental"]],
["Sonata No 1 Op 4", "c minor", "Chopin", 26, 3, "Romantic", ["legendary"]],
["Sonata No 2 Op 35", "bb minor", "Chopin", 24, 3, "Romantic", ["legendary"]],
["Sonata No 3 Op 58", "b minor", "Chopin", 25, 2, "Romantic", ["legendary"]],
["Tarantella Op 43", "Ab Major", "Chopin", 4, 4, "Romantic", []],
["Waltz Op 18", "Eb Major", "Chopin", 5, 4, "Romantic", []],
["Waltz Op 34 No 1", "Ab Major", "Chopin", 5, 5, "Romantic", []],
["Waltz Op 34 No 2", "a minor", "Chopin", 6, 5, "Romantic", []],
["Waltz Op 34 No 3", "F Major", "Chopin", 3, 5, "Romantic", []],
["Waltz Op 42", "Ab Major", "Chopin", 4, 4, "Romantic", []],
["Waltz Op 64 No 1", "Db Major", "Chopin", 2, 4, "Romantic", []],
["Waltz Op 64 No 2", "c# minor", "Chopin", 3, 5, "Romantic", []],
["Waltz Op 64 No 3", "Ab Major", "Chopin", 4, 5, "Romantic", []],
["Waltz Op 69 No 1", "Ab Major", "Chopin", 4, 5, "Romantic", []],
["Waltz Op 69 No 2", "b minor", "Chopin", 3, 5, "Romantic", []],
["Waltz Op 70 No 1", "F# Major", "Chopin", 2, 5, "Romantic", []],
["Waltz Op 70 No 2", "f minor", "Chopin", 4, 5, "Romantic", []],
["Waltz Op 70 No 3", "Db Major", "Chopin", 3, 5, "Romantic", []],
["Waltz Op Posth B 21", "Ab Major", "Chopin", 3, 5, "Romantic", []],
["Waltz Op Posth B 56", "e minor", "Chopin", 3, 4, "Romantic", ["dark"]],
["Waltz Op Posth B 150", "a minor", "Chopin", 2, 5, "Romantic", []],
["Cat and Mouse", "", "Copland", 4, 4, "Contemporary", ["troll"]],
["And the Moon Sets over the Temple That Was", "", "Debussy", 5, 5, "Romantic", ["impressions"]],
["Arabesque No 1", "E Major", "Debussy", 5, 3, "Romantic", ["sleepy", "impressions"]],
["Arabesque No 2", "G Major", "Debussy", 4, 4, "Romantic", []],
["Bells Through the Leaves", "", "Debussy", 5, 5, "Romantic", ["impressions"]],
["Clair De Lune", "Db Major", "Debussy", 6, 2, "Romantic", ["tender", "sleepy", "zen"]],
["Danse Bohemienne", "b minor", "Debussy", 2, 5, "Romantic", []],
["Doctor Gradus ad Parnassum", "C Major", "Debussy", 2, 5, "Romantic", []],
["Evening in Granada from Estampes", "f# minor", "Debussy", 6, 3, "Romantic", ["impressions"]],
["Gardens in the Rain from Estampes", "e minor", "Debussy", 4, 3, "Romantic", []],
["Goldfish", "F# Major", "Debussy", 4, 5, "Romantic", ["impressions"]],
["Golliwoggs Cakewalk", "Eb Major", "Debussy", 4, 5, "Romantic", []],
["Hommage a Rameau", "", "Debussy", 6, 5, "Romantic", ["impressions"]],
["La Cathedrale Engloutie", "C Major", "Debussy", 7, 4, "Romantic", ["impressions"]],
["La Fille aux Cheveux de Lin", "Gb Major", "Debussy", 3, 5, "Romantic", ["impressions"]],
["Lisle Joyeuse", "A Major", "Debussy", 6, 4, "Romantic", ["impressions"]],
["Mouvement", "C Major", "Debussy", 4, 5, "Romantic", ["stamina"]],
["Nocturne L 82", "Db Major", "Debussy", 7, 5, "Romantic", ["impressions"]],
["Pagodas from Estampes", "B Major", "Debussy", 6, 3, "Romantic", ["impressions"]],
["Passapied", "f# minor", "Debussy", 4, 5, "Romantic", []],
["Prelude from Suite Bergamasque", "F Major", "Debussy", 5, 4, "Romantic", []],
["Prelude L 117 No 3", "", "Debussy", 3, 5, "Romantic", []],
["Prelude L 117 No 8", "", "Debussy", 3, 5, "Romantic", []],
["Reflections in the Water", "Db Major", "Debussy", 5, 3,  "Romantic", ["sleepy", "impressions"]],
["Reverie", "F Major", "Debussy", 5, 4, "Romantic", []],
["The Little Shepherd", "A Major", "Debussy", 3, 5, "Romantic", []],
["Cello Concerto Op 104 Mvt 1", "b minor", "Dvorak", 16, 4, "Romantic", []],
["Cello Concerto Op 104 Mvt 2", "G Major", "Dvorak", 14, 5, "Romantic", ["uplifting"]],
["Cello Concerto Op 104 Mvt 3", "b minor", "Dvorak", 14, 5, "Romantic", []],
["New World Symphony Mvt 1", "e minor", "Dvorak", 13, 5, "Romantic", []],
["New World Symphony Mvt 2", "Db Major", "Dvorak", 13, 4, "Romantic", ["uplifting"]],
["New World Symphony Mvt 3", "e minor", "Dvorak", 9, 5, "Romantic", []],
["New World Symphony Mvt 4", "e minor", "Dvorak", 13, 5, "Romantic", []],
["Pavane Op 50", "f# minor", "Faure", 8, 4, "Romantic", []],
["Sicilienne Op 80 No 4", "g minor", "Faure", 5, 4, "Romantic", ["tender"]],
["Nocturne H 24", "Eb Major", "Field", 4, 5, "Romantic", ["sleepy"]],
["Nocturne H 25", "c minor", "Field", 4, 5, "Romantic", ["sleepy"]],
["Nocturne H 37", "Bb Major", "Field", 4, 4, "Romantic", ["sleepy"]],
["Nocturne H 56", "Eb Major", "Field", 6, 4, "Romantic", ["sleepy"]],
["Harp Concerto Mvt 1", "Eb Major", "Gliere", 12, 5, "Contemporary", []],
["Harp Concerto Mvt 2", "Cb Major", "Gliere", 6, 5, "Contemporary", []],
["Harp Concerto Mvt 3", "Eb Major", "Gliere", 13, 4, "Contemporary", []],
["Horn Concerto Mvt 1", "Bb Major", "Gliere", 13, 4, "Contemporary", []],
["Horn Concerto Mvt 2", "Eb Major", "Gliere", 7, 4, "Contemporary", ["tender"]],
["Horn Concerto Mvt 3", "Bb Major", "Gliere", 7, 4, "Contemporary", []],
["The Lark", "bb minor", "Glinka", 6, 3, "Romantic", ["sad"]],
["March of the Trolls Op 54 No 3", "d minor", "Grieg", 2, 3, "Romantic", ["stamina"]],
["Notturno Op 54 No 4", "a minor", "Grieg", 4, 4, "Romantic", []],
["Piano Concerto Op 16 Mvt 1", "a minor", "Grieg", 15, 3, "Romantic", []],
["Piano Concerto Op 16 Mvt 2", "Db Major", "Grieg", 8, 3, "Romantic", ["uplifting", "tender", "sleepy"]],
["Piano Concerto Op 16 Mvt 3", "a minor", "Grieg", 11, 3, "Romantic", ["stamina"]],
["Peer Gynt Suite No 1", "E Major", "Grieg", 15, 3, "Romantic", []],
["Peer Gynt Suite No 2", "g minor", "Grieg", 17, 4, "Romantic", []],
["Hallelujah", "D Major", "Handel", 5, 5, "Baroque", []],
["Piano Concerto No 11 Mvt 1", "D Major", "Haydn", 9, 4, "Classical", []],
["Piano Concerto No 11 Mvt 2", "A Major", "Haydn", 9, 4, "Classical", []],
["Piano Concerto No 11 Mvt 3", "D Major", "Haydn", 5, 4, "Classical", ["stamina"]],
["Piano Sonata No 50", "D Major", "Haydn", 6, 4, "Classical", ["stamina"]],
["Symphony No 47 Mvt 3", "G Major", "Haydn", 3, 5, "Classical", ["troll"]],
["Liebeslied", "a minor", "Kreisler", 4, 5, "Contemporary", ["sad"]],
["Danza Lucumi", "Db Major", "Lecuona", 3, 4, "Contemporary", []],
["Malaguena", "c# minor", "Lecuona", 4, 4, "Contemporary", []],
["Gargoyles", "", "Liebermann", 10, 4, "Contemporary", ["troll"]],
["Piano Concerto No 1 S 124", "Eb Major", "Liszt", 19, 2, "Romantic", ["experimental"]],
["Piano Concerto No 2 S 125", "A Major", "Liszt", 23, 4, "Romantic", ["experimental"]],
["Transcendental Etude S 139 No 3", "F Major", "Liszt", 5, 4, "Romantic", ["sleepy"]],
["Transcendental Etude S 139 No 8", "c minor", "Liszt", 6, 5, "Romantic", []],
["Etude S 141 No 1", "g minor", "Liszt", 5, 4, "Romantic", []],
["Etude S 141 No 2", "Eb Major", "Liszt", 6, 4, "Romantic", []],
["La Campanella S 141 No 3", "g# minor", "Liszt", 5, 4, "Romantic", []],
["Etude S 141 No 4", "E Major", "Liszt", 2, 4, "Romantic", []],
["Etude S 141 No 5", "E Major", "Liszt", 3, 4, "Romantic", []],
["Etude S 141 No 6", "a minor", "Liszt", 5, 4, "Romantic", []],
["Il Lamento S 144 No 1", "Ab Major", "Liszt", 10, 5, "Romantic", []],
["La Leggierezza S 144 No 2", "f minor", "Liszt", 5, 2, "Romantic", ["dark"]],
["Un Sospiro S 144 No 3", "Db Major", "Liszt", 6, 2, "Romantic", ["tender", "sleepy", "zen"]],
["Waldesrauschen S 145 No 1", "Db Major", "Liszt", 5, 2, "Romantic", ["tender", "sleepy", "zen"]],
["Gnomenreigen S 145 No 2", "f# minor", "Liszt", 3, 4, "Romantic", []],
["Seven Brilliant Variations on a Theme of Rossini S 149", "A Major", "Liszt", 10, 4, "Romantic", []],
["Ranz de Vaches S 156 No 17", "G Major", "Liszt", 11, 5, "Romantic", []],
["Un Soir Dans la Montagne S 156 No 18", "C Major", "Liszt", 9, 5, "Romantic", []],
["Ranz de Chevres S 156 No 19", "G Major", "Liszt", 8, 4, "Romantic", []],
["Au lac de Wallenstadt S 160 No 2", "Ab Major", "Liszt", 4, 2, "Romantic", ["tender", "sleepy"]],
["Pastorale S 160 No 3", "E Major", "Liszt", 2, 5, "Romantic", []],
["Au bord dune source S 160 No 4", "Ab Major", "Liszt", 4, 4, "Romantic", ["tender", "sleepy"]],
["Orage S 160 No 5", "c minor", "Liszt", 5, 5, "Romantic", ["dark"]],
["Eglogue S 160 No 7", "Ab Major", "Liszt", 4, 3, "Romantic", ["tender", "sleepy"]],
["The Fountains of the Villa dEste S 163 No 4", "F# Major", "Liszt", 8, 5, "Romantic", ["tender", "sleepy"]],
["Elegie S 168", "Ab Major", "Liszt", 8, 4, "Romantic", []],
["Ballade No 1 S 170", "Db Major", "Liszt", 8, 4, "Romantic", ["experimental"]],
["Ballade No 2 S 171", "b minor", "Liszt", 16, 4, "Romantic", ["experimental"]],
["Consolation S 172 No 1", "E Major", "Liszt", 2, 4, "Romantic", ["tender", "sleepy"]],
["Consolation S 172 No 2", "E Major", "Liszt", 4, 4, "Romantic", ["tender", "sleepy"]],
["Consolation S 172 No 3", "Db Major", "Liszt", 6, 2, "Romantic", ["tender", "sleepy", "zen"]],
["Consolation S 172 No 4", "Db Major", "Liszt", 4, 5, "Romantic", ["tender"]],
["Consolation S 172 No 5", "E Major", "Liszt", 3, 4, "Romantic", ["tender", "sleepy"]],
["Consolation S 172 No 6", "E Major", "Liszt", 3, 4, "Romantic", ["tender", "sleepy"]],
["Ave Maria S 173 No 2", "Bb Major", "Liszt", 9, 4, "Romantic", ["tender", "sleepy"]],
["Benediction de Dieu dans la solitude S 173 No 3", "F# Major", "Liszt", 18, 1, "Romantic", ["legendary", "tender", "sleepy", "zen"]],
["Hymne de lenfant a son reveil S 173 No 6", "Ab Major", "Liszt", 7, 4, "Romantic", ["tender"]],
["Sonata S 178", "b minor", "Liszt", 31, 2, "Romantic", ["dark", "experimental", "legendary"]],
["Berceuse S 186 No 7", "F# Major", "Liszt", 4, 4, "Romantic", ["tender", "sleepy"]],
["Grand Galop Chromatique S 219", "Eb Major", "Liszt", 4, 3, "Romantic", ["stamina"]],
["Galop de Bal S 220", "Bb Major", "Liszt", 1, 4, "Romantic", ["stamina"]],
["Hungarian Rhapsody S 244 No 2", "c# minor", "Liszt", 9, 4, "Romantic", ["dark"]],
["Ballade Ukraine S 249 No 1", "b minor", "Liszt", 9, 5, "Romantic", []],
["Melodies Polonaises S 249 No 2", "Ab Major", "Liszt", 5, 4, "Romantic", []],
["Complainte S 249 No 3", "c# minor", "Liszt", 6, 5, "Romantic", []],
["The Nightingale S 250", "c# minor", "Liszt", 4, 4, "Romantic", []],
["Rondo El Contrabandista S 252", "g minor", "Liszt", 12, 4, "Romantic", ["experimental", "stamina"]],
["Spanish Fantasy S 253", "D Major", "Liszt", 13, 4, "Romantic", []],
["Russian Galop S 478", "Bb Major", "Liszt", 3, 4, "Romantic", ["stamina"]],
["The Maidens Wish S 480 No 1", "G Major", "Liszt", 5, 4, "Romantic", []],
["Spring S 480 No 2", "g minor", "Liszt", 3, 4, "Romantic", []],
["The Ring S 480 No 3", "Eb Major", "Liszt", 4, 5, "Romantic", []],
["Drinking Song S 480 No 4", "C Major", "Liszt", 2, 5, "Romantic", []],
["My Darling S 480 No 5", "Gb Major", "Liszt", 4, 5, "Romantic", []],
["Return Home S 480 No 6", "c minor", "Liszt", 2, 5, "Romantic", []],
["Mephisto Waltz S 514 No 1", "A Major", "Liszt", 12, 3, "Romantic", ["experimental", "stamina"]],
["Liebestraum S 541 No 1", "Ab Major", "Liszt", 8, 4, "Romantic", ["tender"]],
["Liebestraum S 541 No 2", "Eb Major", "Liszt", 5, 5, "Romantic", []],
["Liebestraum S 541 No 3", "Ab Major", "Liszt", 5, 2, "Romantic", ["tender"]],
["Meditation from Thais", "D Major", "Massenet", 5, 5, "Romantic", ["tender"]],
["Intermezzo from Cavalleria Rusticana", "F Major", "Mascagni", 4, 4, "Romantic", []],
["Caprice Op 5", "f# minor", "Mendelssohn", 7, 4, "Romantic", []],
["Caprice Op 33 No 1", "a minor", "Mendelssohn", 9, 3, "Romantic", []],
["Caprice Op 33 No 2", "E Major", "Mendelssohn", 9, 3, "Romantic", []],
["Caprice Op 33 No 3", "bb minor", "Mendelssohn", 7, 5, "Romantic", []],
["Etude WoO 1", "f minor", "Mendelssohn", 2, 4, "Romantic", []],
["Fantasia Op 15", "E Major", "Mendelssohn", 9, 4, "Romantic", []],
["Piano Concerto No 1 Mvt 1", "g minor", "Mendelssohn", 7, 3, "Romantic", ["dark", "stamina"]],
["Piano Concerto No 1 Mvt 2", "E Major", "Mendelssohn", 7, 3, "Romantic", ["tender"]],
["Piano Concerto No 1 Mvt 3", "G Major", "Mendelssohn", 6, 3, "Romantic", ["stamina"]],
["Piano Concerto No 2 Mvt 1", "d minor", "Mendelssohn", 10, 4, "Romantic", ["dark"]],
["Piano Concerto No 2 Mvt 2", "Bb Major", "Mendelssohn", 7, 2, "Romantic", ["tender", "sleepy"]],
["Piano Concerto No 2 Mvt 3", "D Major", "Mendelssohn", 7, 4, "Romantic", []],
["Rondo Capriccioso Op 14", "e minor", "Mendelssohn", 7, 3, "Romantic", []],
["Scherzo a Capriccio", "f# minor", "Mendelssohn", 7, 4, "Romantic", []],
["Songs Without Words Op 19 No 6", "g minor", "Mendelssohn", 2, 5, "Romantic", ["sad"]],
["Songs Without Words Op 30 No 6", "f# minor", "Mendelssohn", 3, 5, "Romantic", ["sad"]],
["Songs Without Words Op 38 No 2", "c minor", "Mendelssohn", 2, 5, "Romantic", []],
["Violin Concerto Mvt 1", "e minor", "Mendelssohn", 13, 5, "Romantic", ["sad"]],
["Violin Concerto Mvt 2", "C Major", "Mendelssohn", 9, 5, "Romantic", ["tender"]],
["Violin Concerto Mvt 3", "E Major", "Mendelssohn", 7, 5, "Romantic", []],
["Wedding March from A Midsummer Nights Dream", "C Major", "Mendelssohn", 10, 4, "Romantic", []],
["Piano Concerto Op 59 Mvt 1", "E Major", "Moszkowski", 13, 4, "Romantic", ["uplifting"]],
["Piano Concerto Op 59 Mvt 2", "c# minor", "Moszkowski", 9, 4, "Romantic", ["dark"]],
["Piano Concerto Op 59 Mvt 3", "c# minor", "Moszkowski", 8, 4, "Romantic", ["stamina"]],
["Piano Concerto Op 59 Mvt 4", "E Major", "Moszkowski", 10, 4, "Romantic", ["stamina"]],
["12 Variations Ah vous diraisje maman", "C Major", "Mozart", 9, 4, "Classical", []],
["Clarinet Concerto Mvt 1", "A Major", "Mozart", 13, 3, "Classical", []],
["Clarinet Concerto Mvt 2", "D Major", "Mozart", 8, 3, "Classical", ["uplifting"]],
["Clarinet Concerto Mvt 3", "A Major", "Mozart", 9, 4, "Classical", []],
["Eine Kleine Nachtmusik", "G Major", "Mozart", 6, 5, "Classical", []],
["Fantasia K 397", "d minor", "Mozart", 6, 3, "Classical", ["sad"]],
["Lacrimosa", "d minor", "Mozart", 4, 5, "Classical", ["sad"]],
["Piano Concerto No 21 Mvt 1", "C Major", "Mozart", 14, 4, "Classical", []],
["Piano Concerto No 21 Mvt 2", "F Major", "Mozart", 7, 4, "Classical", ["sleepy"]],
["Piano Concerto No 21 Mvt 3", "C Major", "Mozart", 7, 4, "Classical", ["stamina"]],
["Piano Concerto No 23 Mvt 1", "A Major", "Mozart", 12, 3, "Classical", []],
["Piano Concerto No 23 Mvt 2", "f# minor", "Mozart", 8, 3, "Classical", ["sad"]],
["Piano Concerto No 23 Mvt 3", "A Major", "Mozart", 9, 3, "Classical", ["stamina"]],
["Sonata No 18", "D Major", "Mozart", 14, 5, "Classical", []],
["Symphony No 40 Mvt 1", "g minor", "Mozart", 6, 5, "Classical", []],
["Symphony No 41 Mvt 4", "C Major", "Mozart", 7, 5, "Classical", ["stamina"]],
["Night on Bald Mountain", "d minor", "Mussorgsky", 10, 5, "Romantic", ["stamina"]],
["Galop Infernal", "D Major", "Offenbach", 6, 4, "Romantic", []],
["Caprice 24", "a minor", "Paganini", 5, 4, "Romantic", []],
["La Campanella", "b minor", "Paganini", 5, 5, "Romantic", []],
["Improvisation No 15", "c minor", "Poulenc", 4, 4, "Contemporary", ["tender"]],
["Dance of the Knights", "e minor", "Prokofiev", 6, 5, "Contemporary", ["dark", "troll"]],
["Musettas Waltz", "E Major", "Puccini", 4, 4, "Romantic", []],
["Elegie Op 3 No 1", "eb minor", "Rachmaninoff", 6, 4, "Romantic", ["sleepy, impressions"]],
["Etude-Tableaux Op 33 No 2", "c minor", "Rachmaninoff", 3, 5, "Contemporary", ["impressions"]],
["Etude-Tableaux Op 33 No 4", "d minor", "Rachmaninoff", 4, 5, "Contemporary", ["impressions"]],
["Etude-Tableaux Op 33 No 5", "eb minor", "Rachmaninoff", 2, 5, "Contemporary", ["impressions"]],
["Etude-Tableaux Op 33 No 6", "Eb Major", "Rachmaninoff", 2, 2, "Contemporary", ["stamina"]],
["Etude-Tableaux Op 33 No 7", "g minor", "Rachmaninoff", 4, 4, "Contemporary", ["impressions"]],
["Etude-Tableaux Op 39 No 1", "c minor", "Rachmaninoff", 3, 4, "Contemporary", ["impressions"]],
["Etude-Tableaux Op 39 No 2", "a minor", "Rachmaninoff", 7, 3, "Contemporary", ["impressions"]],
["Etude-Tableaux Op 39 No 3", "f# minor", "Rachmaninoff", 3, 5, "Contemporary", ["impressions"]],
["Etude-Tableaux Op 39 No 5", "eb minor", "Rachmaninoff", 6, 5, "Contemporary", ["dark", "impressions"]],
["Etude-Tableaux Op 39 No 8", "d minor", "Rachmaninoff", 4, 5, "Contemporary", ["impressions"]],
["Etude-Tableaux Op 39 No 9", "D Major", "Rachmaninoff", 4, 5, "Contemporary", ["impressions"]],
["Italian Polka", "eb minor", "Rachmaninoff", 4, 3, "Romantic", ["dark"]],
["Melody Op 3 No 3", "E Major", "Rachmaninoff", 5, 4, "Romantic", ["sleepy, impressions"]],
["Moments Musicaux Op 16 No 1", "bb minor", "Rachmaninoff", 7, 5, "Romantic", ["impressions"]],
["Moments Musicaux Op 16 No 4", "e minor", "Rachmaninoff", 4, 5, "Romantic", []],
["Moments Musicaux Op 16 No 5", "Db Major", "Rachmaninoff", 4, 4, "Romantic", ["sleepy, impressions"]],
["Moments Musicaux Op 16 No 6", "C Major", "Rachmaninoff", 5, 5, "Romantic", []],
["Morceaux de Salon Op 10 No 2", "A Major", "Rachmaninoff", 4, 4, "Contemporary", []],
["Morceaux de Salon Op 10 No 5", "G Major", "Rachmaninoff", 4, 4, "Contemporary", []],
["Piano Concerto No 1 Mvt 1", "f# minor", "Rachmaninoff", 13, 4, "Romantic", ["legendary"]],
["Piano Concerto No 1 Mvt 2", "D Major", "Rachmaninoff", 7, 4, "Romantic", []],
["Piano Concerto No 1 Mvt 3", "f# minor", "Rachmaninoff", 8, 4, "Romantic", []],
["Piano Concerto No 2 Mvt 1", "c minor", "Rachmaninoff", 12, 1, "Romantic", ["dark", "legendary"]],
["Piano Concerto No 2 Mvt 2", "E Major", "Rachmaninoff", 13, 2, "Romantic", ["uplifting", "legendary"]],
["Piano Concerto No 2 Mvt 3", "c minor", "Rachmaninoff", 12, 3, "Romantic", []],
["Piano Concerto No 3 Mvt 1", "d minor", "Rachmaninoff", 17, 3, "Romantic", []],
["Piano Concerto No 3 Mvt 2", "d minor", "Rachmaninoff", 12, 4, "Romantic", []],
["Piano Concerto No 3 Mvt 3", "d minor", "Rachmaninoff", 15, 4, "Romantic", ["stamina"]],
["Piano Sonata No 2", "bb minor", "Rachmaninoff", 23, 3, "Contemporary", ["legendary", "dark", "experimental"]],
["Polichinelle Op 3 No 4", "f# minor", "Rachmaninoff", 4, 4, "Romantic", ["impressions"]],
["Prelude Op 3 No 2", "c# minor", "Rachmaninoff", 4, 3, "Romantic", ["dark"]],
["Prelude Op 23 No 5", "g minor", "Rachmaninoff", 4, 4, "Romantic", ["stamina"]],
["Prelude Op 23 No 7", "c minor", "Rachmaninoff", 4, 5, "Romantic", ["impressions"]],
["Prelude Op 32 No 5", "G Major", "Rachmaninoff", 4, 3, "Romantic", ["uplifting", "sleepy, impressions"]],
["Prelude Op 32 No 12", "g# minor", "Rachmaninoff", 3, 4, "Romantic", []],
["Rhapsody on a Theme by Paganini", "a minor", "Rachmaninoff", 25, 3, "Contemporary", []],
["Serenade Op 3 No 5", "bb minor", "Rachmaninoff", 4, 5, "Romantic", []],
["Symphony 2 Op 27 Mvt 1", "e minor", "Rachmaninoff", 21, 1, "Romantic", ["legendary"]],
["Symphony 2 Op 27 Mvt 2", "a minor", "Rachmaninoff", 11, 1, "Romantic", ["legendary", "stamina"]],
["Symphony 2 Op 27 Mvt 3", "A Major", "Rachmaninoff", 15, 1, "Romantic", ["legendary", "uplifting"]],
["Symphony 2 Op 27 Mvt 4", "E Major", "Rachmaninoff", 15, 1, "Romantic", ["legendary", "stamina"]],
["Variations on a Theme by Chopin", "c minor", "Rachmaninoff", 27, 4, "Romantic", []],
["Alborada del Gracioso", "", "Ravel", 7, 5, "Contemporary", []],
["Bolero", "C Major", "Ravel", 15, 5, "Contemporary", ["troll"]],
["La Vallee des Cloches", "", "Ravel", 6, 4, "Contemporary", ["impressions"]],
["Noctuelles", "", "Ravel", 5, 5, "Contemporary", ["impressions"]],
["Oiseaux Tristes", "", "Ravel", 4, 5, "Contemporary", ["impressions"]],
["Ondine", "C# Major", "Ravel", 7, 3, "Contemporary", ["impressions"]],
["Pavane for Dead Princess", "G Major", "Ravel", 7, 5, "Contemporary", []],
["Une Barque sur la Ocean", "A Major", "Ravel", 7, 4, "Contemporary", ["impressions"]],
["Piano Concerto Mvt 1", "G Major", "Ravel", 9, 5, "Contemporary", ["troll"]],
["Piano Concerto Mvt 2", "E Major", "Ravel", 10, 5, "Contemporary", ["troll"]],
["Piano Concerto Mvt 3", "G Major", "Ravel", 4, 5, "Contemporary", ["troll"]],
["Intermezzo Serenata", "E Major", "Respighi", 3, 3, "Romantic", ["tender", "sleepy"]],
["Valse Caressante", "Eb Major", "Respighi", 4, 3, "Romantic", ["tender", "sleepy"]],
["Capriccio Espagnol", "A Major", "RimskyKorsakov", 16, 1, "Romantic", ["stamina"]],
["Flight of the Bumblebee", "a minor", "RimskyKorsakov", 1, 5, "Romantic", ["troll"]],
["Procession of Nobles", "Eb Major", "RimskyKorsakov", 5, 5, "Romantic", []],
["Barber of Seville", "E Major", "Rossini", 8, 4, "Romantic", []],
["William Tell Overture Finale", "E Major", "Rossini", 4, 4, "Romantic", ["stamina"]],
["Aquarium", "a minor", "SaintSaens", 3, 4, "Romantic", ["sleepy, impressions"]],
["Aviary", "F Major", "SaintSaens", 2, 4, "Romantic", ["uplifting", "sleepy"]],
["Bacchanale from Samson and Delilah", "d minor", "SaintSaens", 8, 5, "Romantic", []],
["Danse Macabre", "g minor", "SaintSaens", 8, 3, "Romantic", ["dark"]],
["Introduction and Rondo Capriccioso Op 28", "a minor", "SaintSaens", 9, 5, "Romantic", ["sad"]],
["Piano Concerto No 2 Mvt 1", "g minor", "SaintSaens", 14, 3, "Romantic", []],
["Piano Concerto No 2 Mvt 2", "Eb Major", "SaintSaens", 7, 3, "Romantic", []],
["Piano Concerto No 2 Mvt 3", "g minor", "SaintSaens", 7, 3, "Romantic", ["dark", "stamina"]],
["Piano Concerto No 4 Mvt 1", "c minor", "SaintSaens", 13, 3, "Romantic", []],
["Piano Concerto No 4 Mvt 2", "C Major", "SaintSaens", 14, 4, "Romantic", []],
["Piano Concerto No 5 Mvt 1", "F Major", "SaintSaens", 10, 4, "Romantic", []],
["Piano Concerto No 5 Mvt 2", "d minor", "SaintSaens", 11, 3, "Romantic", []],
["Piano Concerto No 5 Mvt 3", "F Major", "SaintSaens", 6, 2, "Romantic", ["stamina"]],
["The Swan", "G Major", "SaintSaens", 3, 3, "Romantic", ["tender", "sleepy"]],
["Violin Concerto No 3 Mvt 1", "b minor", "SaintSaens", 10, 5, "Romantic", []],
["Gymnopedie No 1", "D Major", "Satie", 4, 5, "Romantic", ["troll"]],
["Gnossienne No 1", "f minor", "Satie", 4, 4, "Romantic", ["tender", "sleepy"]],
["Je te veux", "C Major", "Satie", 5, 4, "Romantic", []],
["Humoresque", "Db Major", "Schedrin", 2, 5, "Contemporary", ["troll"]],
["Ave Maria", "Bb Major", "Schubert", 5, 3, "Romantic", ["tender", "sleepy"]],
["Gretchen am Spinnrade", "d minor", "Schubert", 3, 5, "Romantic", []],
["Erlkonig", "g minor", "Schubert", 5, 4, "Romantic", ["dark"]],
["Impromptu Op 90 No 1", "c minor", "Schubert", 10, 4, "Romantic", ["sad"]],
["Impromptu Op 90 No 2", "Eb Major", "Schubert", 5, 5, "Romantic", []],
["Impromptu Op 90 No 3", "Gb Major", "Schubert", 7, 5, "Romantic", ["sleepy"]],
["Impromptu Op 90 No 4", "Ab Major", "Schubert", 7, 5, "Romantic", []],
["Impromptu Op 142 No 1", "f minor", "Schubert", 12, 5, "Romantic", []],
["Impromptu Op 142 No 2", "Ab Major", "Schubert", 8, 5, "Romantic", []],
["Impromptu Op 142 No 3", "Bb Major", "Schubert", 12, 4, "Romantic", ["tender", "sleepy"]],
["Impromptu Op 142 No 4", "f minor", "Schubert", 6, 5, "Romantic", []],
["Serenade", "d minor", "Schubert", 4, 5, "Romantic", ["sad"]],
["Symphony No 8 Mvt 1", "b minor", "Schubert", 14, 3, "Romantic", []],
["Symphony No 8 Mvt 2", "E Major", "Schubert", 13, 4, "Romantic", []],
["Wanderer Fantasy Op 15", "C Major", "Schubert", 21, 4, "Romantic", ["legendary"]],
["Aufschwung Op 12 No 2", "f minor", "Schumann", 4, 5, "Romantic", []],
["Dreaming Op 15 No 7", "F Major", "Schumann", 3, 5, "Romantic", ["sleepy"]],
["Des Abends Op 12 No 1", "Db Major", "Schumann", 4, 5, "Romantic", ["sleepy"]],
["In der Nacht Op 12 No 5", "f minor", "Schumann", 4, 5, "Romantic", ["dark"]],
["Of Foreign Lands and Peoples", "G Major", "Schumann", 2, 5, "Romantic", ["sleepy"]],
["Piano Concerto Op 54 Mvt 1", "a minor", "Schumann", 13, 5, "Romantic", []],
["Piano Concerto Op 54 Mvt 2", "F Major", "Schumann", 5, 4, "Romantic", []],
["Piano Concerto Op 54 Mvt 3", "A Major", "Schumann", 11, 5, "Romantic", []],
["Sonata No 1 Op 11", "f# minor", "Schumann", 30, 5, "Romantic", []],
["Sonata No 2 Op 22", "g minor", "Schumann", 12, 3, "Romantic", ["dark", "legendary"]],
["Widmung", "Ab Major", "Schumann", 4, 4, "Romantic", ["tender"]],
["Etude Op 8 No 12", "d# minor", "Scriabin", 3, 4, "Romantic", ["dark"]],
["Etude Op 42 No 5", "c# minor", "Scriabin", 3, 4, "Romantic", ["dark", "impressions"]],
["Prelude Op 11 No 1", "C Major", "Scriabin", 1, 5, "Romantic", ["impressions"]],
["Prelude Op 11 No 8", "f# minor", "Scriabin", 2, 5, "Romantic", ["dark"]],
["Prelude Op 11 No 10", "c# minor", "Scriabin", 2, 5, "Romantic", []],
["Sonata No 2", "g# minor", "Scriabin", 15, 3, "Romantic", ["experimental", "legendary"]],
["Piano Concerto No 2 Mvt 1", "F Major", "Shostakovich", 8, 3, "Contemporary", ["stamina"]],
["Piano Concerto No 2 Mvt 2", "c minor", "Shostakovich", 7, 2, "Contemporary", ["tender", "sleepy", "impressions"]],
["Piano Concerto No 2 Mvt 3", "F Major", "Shostakovich", 6, 3, "Contemporary", ["stamina"]],
["Waltz No 2", "c minor", "Shostakovich", 4, 5, "Contemporary", []],
["Karelia Suite", "Eb Major", "Sibelius", 17, 4, "Romantic", []],
["The Spruce Op 75 No 5", "D Major", "Sibelius", 4, 4, "Romantic", []],
["La Moldau", "e minor", "Smetana", 14, 4, "Romantic", []],
["Blue Danube", "D Major", "Strauss", 10, 3, "Romantic", ["uplifting"]],
["Fledermaus Overture", "A Major", "Strauss", 9, 4, "Romantic", []],
["Voices of Spring", "Bb Major", "Strauss", 6, 4, "Romantic", []],
["Dance of the Little Swans", "f# minor", "Tchaikovsky", 2, 5, "Romantic", []],
["Dance of the Suger Plum Fairy", "e minor", "Tchaikovsky", 2, 5, "Romantic", []],
["March from The Seasons", "g minor", "Tchaikovsky", 3, 5, "Romantic", ["sad", "tender"]],
["Marche", "G Major", "Tchaikovsky", 3, 5, "Romantic", ["stamina"]],
["June from The Seasons", "g minor", "Tchaikovsky", 5, 5, "Romantic", ["sad", "tender"]],
["November from The Seasons", "E Major", "Tchaikovsky", 4, 5, "Romantic", []],
["Pas de Deux", "G Major", "Tchaikovsky", 6, 5, "Romantic", []],
["Piano Concerto No 1 Mvt 1", "bb minor", "Tchaikovsky", 20, 4, "Romantic", []],
["Piano Concerto No 1 Mvt 2", "Db Major", "Tchaikovsky", 7, 3, "Romantic", ["tender", "uplifting"]],
["Piano Concerto No 1 Mvt 3", "bb minor", "Tchaikovsky", 7, 4, "Romantic", ["dark", "stamina"]],
["Sleeping Beauty Waltz", "Bb Major", "Tchaikovsky", 5, 5, "Romantic", []],
["Swan Lake Waltz", "A Major", "Tchaikovsky", 8, 5, "Romantic", []],
["Swan Lake Theme", "b minor", "Tchaikovsky", 3, 5, "Romantic", []],
["Trepak", "G Major", "Tchaikovsky", 2, 5, "Romantic", ["stamina"]],
["Valse Sentimentale Op 51 No 6", "f minor", "Tchaikovsky", 5, 5, "Romantic", ["sad"]],
["Waltz of the Flowers", "D Major", "Tchaikovsky", 7, 5, "Romantic", []],
["Ride of the Valkyries", "b minor", "Wagner", 5, 4, "Romantic", []]];

