const pieces = [["Aragon", "F Major", "Albeniz", 5, 5, "Contemporary", [], ["Suite Espagnola", 6]],
["Asturias", "g minor", "Albeniz", 6, 5, "Contemporary", [], ["Suite Espagnola", 5]],
["Cadiz", "Db Major", "Albeniz", 5, 5, "Contemporary", [], ["Suite Espagnola", 4]],
["Castilla", "F# Major", "Albeniz", 3, 4, "Contemporary", ["stamina"], ["Suite Espagnola", 7]],
["Catalunya", "g minor", "Albeniz", 3, 5, "Contemporary", [], ["Suite Espagnola", 2]],
["Cuba", "Eb Major", "Albeniz", 6, 5, "Contemporary", [], ["Suite Espagnola", 8]],
["Granada", "F Major", "Albeniz", 6, 5, "Contemporary", [], ["Suite Espagnola", 1]],
["Sevilla", "G Major", "Albeniz", 5, 5, "Contemporary", [], ["Suite Espagnola", 3]],
["Concerto No 7 BWV 1058 Mvt 1", "g minor", "Bach", 4, 5, "Baroque", [], ""],
["Invention No 8", "F Major", "Bach", 1, 5, "Baroque", [], ""],
["Prelude and Fugue BWV 881", "f minor", "Bach", 6, 5, "Baroque", [], ""],
["Islamey", "Db Major", "Balakirev", 8, 5, "Romantic", [], ""],
["Hungarian Pictures", "f# minor", "Bartok", 11, 2, "Contemporary", ["impressions"], "Hungarian Pictures"],
["Romanian Folk Dances", "a minor", "Bartok", 6, 4, "Contemporary", [], ""],
["Piano Concerto No 1 Mvt 1", "C Major", "Beethoven", 19, 5, "Classical", [], "Piano Concerto No 1"],
["Piano Concerto No 1 Mvt 2", "Ab Major", "Beethoven", 11, 3, "Classical", [], "Piano Concerto No 1"],
["Piano Concerto No 1 Mvt 3", "C Major", "Beethoven", 9, 5, "Classical", [], "Piano Concerto No 1"],
["Piano Concerto No 3 Mvt 1", "c minor", "Beethoven", 17, 4, "Classical", [], "Piano Concerto No 3"],
["Piano Concerto No 3 Mvt 2", "E Major", "Beethoven", 11, 4, "Classical", [], "Piano Concerto No 3"],
["Piano Concerto No 3 Mvt 3", "c minor", "Beethoven", 9, 4, "Classical", [], "Piano Concerto No 3"],
["Piano Concerto No 4 Mvt 1", "G Major", "Beethoven", 20, 3, "Classical", [], "Piano Concerto No 4"],
["Piano Concerto No 4 Mvt 2", "e minor", "Beethoven", 6, 4, "Classical", [], "Piano Concerto No 4"],
["Piano Concerto No 4 Mvt 3", "G Major", "Beethoven", 10, 3, "Classical", ["stamina"], "Piano Concerto No 4"],
["Piano Concerto No 5 Mvt 1", "Eb Major", "Beethoven", 21, 4, "Classical", [], "Piano Concerto No 5"],
["Piano Concerto No 5 Mvt 2", "B Major", "Beethoven", 9, 3,  "Classical", ["uplifting", "tender"], "Piano Concerto No 5"],
["Piano Concerto No 5 Mvt 3", "Eb Major", "Beethoven", 12, 4, "Classical", [], "Piano Concerto No 5"],
["Rage over a Lost Penny", "G Major", "Beethoven", 6, 4, "Classical", ["stamina"], ""],
["Sonata No 1 Mvt 14", "f minor", "Beethoven", 7, 3, "Classical", ["stamina"], ""],
["Sonata No 2 Mvt 13", "A Major", "Beethoven", 8, 4, "Classical", [], ""],
["Sonata No 3 Mvt 1", "C Major", "Beethoven", 10, 3, "Classical", [], ""],
["Sonata No 4 Mvt 134", "Eb Major", "Beethoven", 18, 4, "Classical", [], ""],
["Sonata No 5 Mvt 1", "c minor", "Beethoven", 4, 5, "Classical", [], ""],
["Sonata No 6 Mvt 13", "F Major", "Beethoven", 6, 4, "Classical", [], ""],
["Sonata No 7 Mvt 1", "D Major", "Beethoven", 7, 3, "Classical", ["stamina"], ""],
["Sonata No 8", "c minor", "Beethoven", 20, 3, "Classical", [], ""],
["Sonata No 9 Mvt 1", "E Major", "Beethoven", 5, 4, "Classical", ["stamina"], ""],
["Sonata No 10 Mvt 12", "G Major", "Beethoven", 11, 4, "Classical", [], ""],
["Sonata No 11 Mvt 14", "Bb Major", "Beethoven", 15, 3, "Classical", [], ""],
["Sonata No 12 Mvt 3", "ab minor", "Beethoven", 6, 4, "Classical", ["dark"], ""],
["Sonata No 13", "Eb Major", "Beethoven", 16, 4, "Classical", [], ""],
["Sonata No 14", "c# minor", "Beethoven", 15, 3, "Classical", ["dark"], ""],
["Sonata No 15 Mvt 134", "D Major", "Beethoven", 19, 3, "Classical", ["sleepy"], ""],
["Sonata No 16 Mvt 1", "G Major", "Beethoven", 7, 5, "Classical", [], ""],
["Sonata No 17", "d minor", "Beethoven", 23, 3, "Classical", ["dark"], ""],
["Sonata No 18 Mvt 14", "Eb Major", "Beethoven", 10, 4, "Classical", ["stamina"], ""],
["Sonata No 19", "g minor", "Beethoven", 9, 5, "Classical", [], ""],
["Sonata No 20", "G Major", "Beethoven", 7, 5, "Classical", [], ""],
["Sonata No 21 Mvt 13", "C Major", "Beethoven", 18, 3, "Classical", [], ""],
["Sonata No 22", "F Major", "Beethoven", 12, 4, "Classical", [], ""],
["Sonata No 23", "f minor", "Beethoven", 26, 4, "Classical", [], ""],
["Sonata No 24", "F# Major", "Beethoven", 10, 4, "Classical", [], ""],
["Sonata No 25", "G Major", "Beethoven", 12, 4, "Classical", [], ""],
["Sonata No 26 Mvt 13", "Eb Major", "Beethoven", 13, 4, "Classical", [], ""],
["Sonata No 27", "e minor", "Beethoven", 14, 3, "Classical", [], "Late Sonatas"],
["Sonata No 28", "A Major", "Beethoven", 21, 2, "Romantic", ["legendary", "uplifting"], "Late Sonatas"],
["Sonata No 29", "Bb Major", "Beethoven", 42, 2, "Romantic", ["legendary"], "Late Sonatas"],
["Sonata No 30", "E Major", "Beethoven", 19, 2, "Romantic", ["legendary"], "Late Sonatas"],
["Sonata No 31", "Ab Major", "Beethoven", 20, 1, "Romantic", ["legendary", "tender"], "Late Sonatas"],
["Sonata No 32", "c minor", "Beethoven", 30, 2, "Romantic", ["legendary", "experimental"], "Late Sonatas"],
["Symphony No 3 Mvt 1", "Eb Major", "Beethoven", 15, 5, "Classical", [], ""],
["Symphony No 5 Mvt 1", "c minor", "Beethoven", 8, 4, "Classical", [], "Symphony No 5"],
["Symphony No 5 Mvt 2", "Ab Major", "Beethoven", 10, 4, "Classical", [], "Symphony No 5"],
["Symphony No 5 Mvt 3", "c minor", "Beethoven", 6, 4, "Classical", [], "Symphony No 5"],
["Symphony No 5 Mvt 4", "C Major", "Beethoven", 9, 4, "Classical", [], "Symphony No 5"],
["Symphony No 7 Mvt 1", "A Major", "Beethoven", 13, 4, "Classical", [], "Symphony No 7"],
["Symphony No 7 Mvt 2", "a minor", "Beethoven", 9, 4, "Classical", [], "Symphony No 7"],
["Symphony No 7 Mvt 3", "F Major", "Beethoven", 9, 4, "Classical", ["stamina"], "Symphony No 7"],
["Symphony No 7 Mvt 4", "A Major", "Beethoven", 7, 4, "Classical", ["stamina"], "Symphony No 7"],
["Symphony No 9 Mvt 1", "d minor", "Beethoven", 18, 5, "Classical", [], "Symphony No 9"],
["Symphony No 9 Mvt 2", "D Major", "Beethoven", 12, 5, "Classical", [], "Symphony No 9"],
["Symphony No 9 Mvt 3", "Bb Major", "Beethoven", 18, 5, "Classical", [], "Symphony No 9"],
["Symphony No 9 Mvt 4", "D Major", "Beethoven", 8, 5, "Classical", ["troll"], "Symphony No 9"],
["Carmen Prelude", "A Major", "Bizet", 3, 4, "Romantic", [], ""],
["Habanera", "D Major", "Bizet", 3, 4, "Romantic", [], ""],
["Toreador Song", "F Major", "Bizet", 3, 4, "Romantic", [], ""],
["Capriccio Op 116 No 3", "g minor", "Brahms", 3, 4, "Romantic", ["stamina"], ""],
["Hungarian Dance No 1", "g minor", "Brahms", 3, 5, "Romantic", [], ""],
["Hungarian Dance No 5", "g minor", "Brahms", 4, 4, "Romantic", [], ""],
["Lullaby Op 49 No 4", "Eb Major", "Brahms", 3, 5, "Romantic", ["sleepy"], ""],
["Piano Concerto No 1 Mvt 1", "d minor", "Brahms", 25, 4, "Romantic", [], "Piano Concerto No 1"],
["Piano Concerto No 1 Mvt 2", "D Major", "Brahms", 15, 4, "Romantic", [], "Piano Concerto No 1"],
["Piano Concerto No 1 Mvt 3", "d minor", "Brahms", 13, 4, "Romantic", [], "Piano Concerto No 1"],
["Piano Concerto No 2 Mvt 1", "Bb Major", "Brahms", 19, 3, "Romantic", ["legendary"], "Piano Concerto No 2"],
["Piano Concerto No 2 Mvt 2", "d minor", "Brahms", 10, 3, "Romantic", ["dark"], "Piano Concerto No 2"],
["Piano Concerto No 2 Mvt 3", "Bb Major", "Brahms", 15, 3, "Romantic", [], "Piano Concerto No 2"],
["Piano Concerto No 2 Mvt 4", "Bb Major", "Brahms", 10, 4, "Romantic", [], "Piano Concerto No 2"],
["Rhapsody Op 79 No 1", "b minor", "Brahms", 9, 2, "Romantic", ["stamina"], "Two Rhapsodies Op 79"],
["Rhapsody Op 79 No 2", "g minor", "Brahms", 7, 3, "Romantic", ["dark"], "Two Rhapsodies Op 79"],
["Sonata No 1", "C Major", "Brahms", 25, 5, "Romantic", [], ""],
["Sonata No 3", "Bb Major", "Brahms", 34, 4, "Romantic", [], ""],
["Variations on a Theme by Paganini Op 35", "a minor", "Brahms", 24, 4, "Romantic", [], ""],
["Andante Spianato Op 22 No 1", "G Major", "Chopin", 5, 2, "Romantic", ["uplifting", "sleepy"], "Andante spianato et grande polonaise brillante"],
["Ballade No 1", "g minor", "Chopin", 10, 3, "Romantic", [], "Four Ballades"],
["Ballade No 2", "F Major", "Chopin", 8, 2, "Romantic", ["legendary"], "Four Ballades"],
["Ballade No 3", "Ab Major", "Chopin", 7, 1, "Romantic", ["legendary"], "Four Ballades"],
["Ballade No 4", "f minor", "Chopin", 12, 4, "Romantic", [], "Four Ballades"],
["Barcarolle Op 60", "F# Major", "Chopin", 9, 4, "Romantic", [], ""],
["Berceuse Op 57", "Db Major", "Chopin", 5, 3, "Romantic", ["tender"], ""],
["Etude Op 10 No 1", "C Major", "Chopin", 2, 4, "Romantic", [], "Etudes Op 10"],
["Etude Op 10 No 2", "a minor", "Chopin", 2, 5, "Romantic", [], "Etudes Op 10"],
["Etude Op 10 No 3", "E Major", "Chopin", 5, 5, "Romantic", [], "Etudes Op 10"],
["Etude Op 10 No 4", "c# minor", "Chopin", 2, 5, "Romantic", [], "Etudes Op 10"],
["Etude Op 10 No 5", "Gb Major", "Chopin", 2, 5, "Romantic", [], "Etudes Op 10"],
["Etude Op 10 No 6", "eb minor", "Chopin", 5, 5, "Romantic", [], "Etudes Op 10"],
["Etude Op 10 No 7", "C Major", "Chopin", 2, 5, "Romantic", [], "Etudes Op 10"],
["Etude Op 10 No 8", "F Major", "Chopin", 3, 5, "Romantic", [], "Etudes Op 10"],
["Etude Op 10 No 9", "f minor", "Chopin", 3, 4, "Romantic", [], "Etudes Op 10"],
["Etude Op 10 No 10", "Ab Major", "Chopin", 3, 5, "Romantic", [], "Etudes Op 10"],
["Etude Op 10 No 11", "Eb Major", "Chopin", 3, 5, "Romantic", [], "Etudes Op 10"],
["Etude Op 10 No 12", "c minor", "Chopin", 3, 5, "Romantic", [], "Etudes Op 10"],
["Etude Op 25 No 1", "Ab Major", "Chopin", 4, 2, "Romantic", ["sleepy"], "Etudes Op 25"],
["Etude Op 25 No 2", "f minor", "Chopin", 2, 5, "Romantic", [], "Etudes Op 25"],
["Etude Op 25 No 3", "F Major", "Chopin", 2, 5, "Romantic", [], "Etudes Op 25"],
["Etude Op 25 No 4", "a minor", "Chopin", 2, 5, "Romantic", [], "Etudes Op 25"],
["Etude Op 25 No 5", "e minor", "Chopin", 4, 5, "Romantic", [], "Etudes Op 25"],
["Etude Op 25 No 6", "g# minor", "Chopin", 3, 5, "Romantic", [], "Etudes Op 25"],
["Etude Op 25 No 7", "c# minor", "Chopin", 6, 5, "Romantic", [], "Etudes Op 25"],
["Etude Op 25 No 8", "Db Major", "Chopin", 2, 5, "Romantic", [], "Etudes Op 25"],
["Etude Op 25 No 9", "Gb Major", "Chopin", 5, 5, "Romantic", ["stamina"], "Etudes Op 25"],
["Etude Op 25 No 10", "b minor", "Chopin", 5, 5, "Romantic", [], "Etudes Op 25"],
["Etude Op 25 No 11", "a minor", "Chopin", 4, 4, "Romantic", ["dark"], "Etudes Op 25"],
["Etude Op 25 No 12", "c minor", "Chopin", 3, 5, "Romantic", [], "Etudes Op 25"],
["Fantaisie Op 49", "Ab Major", "Chopin", 12, 1, "Romantic", ["legendary"], "Fantaisie Op 49"],
["Funeral March Op 72 No 2", "c minor", "Chopin", 6, 5, "Romantic", [], ""],
["Grande polonaise brillante Op 22 No 2", "Eb Major", "Chopin", 10, 4, "Romantic", [], "Andante spianato et grande polonaise brillante"],
["Impromptu No 1 Op 29", "Ab Major", "Chopin", 5, 4, "Romantic", [], "Four Impromptus"],
["Impromptu No 2 Op 36", "F# Major", "Chopin", 6, 5, "Romantic", [], "Four Impromptus"],
["Impromptu No 3 Op 51", "Gb Major", "Chopin", 6, 5, "Romantic", [], "Four Impromptus"],
["Impromptu No 4 Op 66", "c# minor", "Chopin", 5, 4, "Romantic", [], "Four Impromptus"],
["Mazurka Op 59 No 3", "f# minor", "Chopin", 4, 5, "Romantic", [], ""],
["Mazurka Op 67 No 4", "a minor", "Chopin", 4, 5, "Romantic", [], ""],
["Nocturne Op 9 No 1", "bb minor", "Chopin", 6, 4, "Romantic", ["sleepy"], "Nocturnes"],
["Nocturne Op 9 No 2", "Eb Major", "Chopin", 5, 4, "Romantic", ["sleepy"], "Nocturnes"],
["Nocturne Op 9 No 3", "B Major", "Chopin", 7, 4, "Romantic", [], "Nocturnes"],
["Nocturne Op 15 No 1", "F Major", "Chopin", 5, 3, "Romantic", ["sleepy"], "Nocturnes"],
["Nocturne Op 15 No 2", "F# Major", "Chopin", 4, 4, "Romantic", ["sleepy"], "Nocturnes"],
["Nocturne Op 15 No 3", "g minor", "Chopin", 5, 5, "Romantic", [], "Nocturnes"],
["Nocturne Op 27 No 1", "c# minor", "Chopin", 6, 4, "Romantic", [], "Nocturnes"],
["Nocturne Op 27 No 2", "Db Major", "Chopin", 8, 4, "Romantic", ["sleepy"], "Nocturnes"],
["Nocturne Op 32 No 1", "B Major", "Chopin", 6, 4, "Romantic", ["sleepy"], "Nocturnes"],
["Nocturne Op 32 No 2", "Ab Major", "Chopin", 6, 4, "Romantic", [], "Nocturnes"],
["Nocturne Op 37 No 1", "g minor", "Chopin", 7, 5, "Romantic", [], "Nocturnes"],
["Nocturne Op 37 No 2", "G Major", "Chopin", 6, 3, "Romantic", ["sleepy"], "Nocturnes"],
["Nocturne Op 48 No 1", "c minor", "Chopin", 7, 3, "Romantic", ["sad"], "Nocturnes"],
["Nocturne Op 48 No 2", "f# minor", "Chopin", 7, 5, "Romantic", [], "Nocturnes"],
["Nocturne Op 55 No 1", "f minor", "Chopin", 5, 4, "Romantic", [], "Nocturnes"],
["Nocturne Op 55 No 2", "Eb Major", "Chopin", 5, 5, "Romantic", [], "Nocturnes"],
["Nocturne Op 62 No 1", "B Major", "Chopin", 8, 5, "Romantic", [], "Nocturnes"],
["Nocturne Op 62 No 2", "E Major", "Chopin", 6, 5, "Romantic", [], "Nocturnes"],
["Nocturne Op 72 No 1", "e minor", "Chopin", 5, 5, "Romantic", [], "Nocturnes"],
["Nocturne No 20 Op Posth", "c# minor", "Chopin", 4, 4, "Romantic", [], "Nocturnes"],
["Nocturne No 21 Op Posth", "c minor", "Chopin", 4, 5, "Romantic", [], "Nocturnes"],
["Piano Concerto No 1 Op 11 Mvt 1", "e minor", "Chopin", 21, 1, "Romantic", ["legendary"], "Piano Concerto No 1"],
["Piano Concerto No 1 Op 11 Mvt 2", "E Major", "Chopin", 10, 1, "Romantic", ["uplifting"], "Piano Concerto No 1"],
["Piano Concerto No 1 Op 11 Mvt 3", "E Major", "Chopin", 10, 1, "Romantic", ["stamina"], "Piano Concerto No 1"],
["Piano Concerto No 2 Op 21 Mvt 1", "f minor", "Chopin", 16, 3, "Romantic", ["legendary"], "Piano Concerto No 2"],
["Piano Concerto No 2 Op 21 Mvt 2", "Ab Major", "Chopin", 12, 4, "Romantic", ["tender"], "Piano Concerto No 2"],
["Piano Concerto No 2 Op 21 Mvt 3", "f minor", "Chopin", 10, 2, "Romantic", [], "Piano Concerto No 2"],
["Polonaise Fantaisie Op 61", "Ab Major", "Chopin", 14, 4, "Romantic", ["experimental"], ""],
["Polonaise Op 26 No 1", "c# minor", "Chopin", 8, 4, "Romantic", ["dark"], ""],
["Polonaise Op 26 No 2", "eb minor", "Chopin", 8, 3, "Romantic", [], ""],
["Polonaise Op 40 No 1", "A Major", "Chopin", 5, 3, "Romantic", ["stamina"], ""],
["Polonaise Op 40 No 2", "c minor", "Chopin", 8, 5, "Romantic", [], ""],
["Polonaise Op 44", "f# minor", "Chopin", 11, 4, "Romantic", ["dark", "stamina"], ""],
["Polonaise Op 53", "Ab Major", "Chopin", 7, 3, "Romantic", ["stamina"], ""],
["Polonaise Op 71 No 1", "d minor", "Chopin", 6, 5, "Romantic", [], ""],
["Polonaise Op 71 No 2", "Bb Major", "Chopin", 7, 4, "Romantic", [], ""],
["Polonaise Op 71 No 3", "f minor", "Chopin", 8, 5, "Romantic", [], ""],
["Prelude Op 28 No 1", "C Major", "Chopin", 1, 4, "Romantic", [], ""],
["Prelude Op 28 No 11", "B Major", "Chopin", 1, 5, "Romantic", [], ""],
["Prelude Op 28 No 15", "Db Major", "Chopin", 6, 2, "Romantic", ["tender", "zen"], ""],
["Prelude Op 28 No 16", "bb minor", "Chopin", 2, 5, "Romantic", [], ""],
["Prelude Op 28 No 17", "Ab Major", "Chopin", 4, 4, "Romantic", ["sleepy"], ""],
["Prelude Op 28 No 19", "Eb Major", "Chopin", 2, 5, "Romantic", [], ""],
["Prelude Op 28 No 24", "d minor", "Chopin", 3, 5, "Romantic", [], ""],
["Scherzo No 1 Op 20", "b minor", "Chopin", 10, 3, "Romantic", ["experimental"], "Four Scherzos"],
["Scherzo No 2 Op 31", "bb minor", "Chopin", 9, 3, "Romantic", [], "Four Scherzos"],
["Scherzo No 3 Op 39", "C# Major", "Chopin", 8, 3, "Romantic", ["experimental"], "Four Scherzos"],
["Scherzo No 4 Op 54", "E Major", "Chopin", 11, 3, "Romantic", ["experimental"], "Four Scherzos"],
["Sonata No 1 Op 4", "c minor", "Chopin", 26, 3, "Romantic", ["legendary"], "Three Sonatas"],
["Sonata No 2 Op 35", "bb minor", "Chopin", 24, 3, "Romantic", ["legendary"], "Three Sonatas"],
["Sonata No 3 Op 58", "b minor", "Chopin", 25, 2, "Romantic", ["legendary"], "Three Sonatas"],
["Tarantella Op 43", "Ab Major", "Chopin", 4, 4, "Romantic", [], ""],
["Waltz Op 18", "Eb Major", "Chopin", 5, 4, "Romantic", [], "Waltzes"],
["Waltz Op 34 No 1", "Ab Major", "Chopin", 5, 5, "Romantic", [], "Waltzes"],
["Waltz Op 34 No 2", "a minor", "Chopin", 6, 4, "Romantic", [], "Waltzes"],
["Waltz Op 34 No 3", "F Major", "Chopin", 3, 5, "Romantic", [], "Waltzes"],
["Waltz Op 42", "Ab Major", "Chopin", 4, 4, "Romantic", [], "Waltzes"],
["Waltz Op 64 No 1", "Db Major", "Chopin", 2, 4, "Romantic", [], "Waltzes"],
["Waltz Op 64 No 2", "c# minor", "Chopin", 3, 4, "Romantic", [], "Waltzes"],
["Waltz Op 64 No 3", "Ab Major", "Chopin", 4, 5, "Romantic", [], "Waltzes"],
["Waltz Op 69 No 1", "Ab Major", "Chopin", 4, 5, "Romantic", [], "Waltzes"],
["Waltz Op 69 No 2", "b minor", "Chopin", 3, 5, "Romantic", [], "Waltzes"],
["Waltz Op 70 No 1", "F# Major", "Chopin", 2, 5, "Romantic", [], "Waltzes"],
["Waltz Op 70 No 2", "f minor", "Chopin", 4, 5, "Romantic", [], "Waltzes"],
["Waltz Op 70 No 3", "Db Major", "Chopin", 3, 5, "Romantic", [], "Waltzes"],
["Waltz Op Posth B 21", "Ab Major", "Chopin", 3, 5, "Romantic", [], "Waltzes"],
["Waltz Op Posth B 56", "e minor", "Chopin", 3, 4, "Romantic", ["dark"], "Waltzes"],
["Waltz Op Posth B 150", "a minor", "Chopin", 2, 5, "Romantic", [], "Waltzes"],
["Cat and Mouse", "", "Copland", 4, 4, "Contemporary", ["troll"], ""],
["And the Moon Sets over the Temple That Was", "e minor", "Debussy", 5, 5, "Romantic", ["impressions"], ["Images Book 2", 2]],
["Arabesque No 1", "E Major", "Debussy", 5, 3, "Romantic", ["sleepy", "impressions"], "Two Arabesques"],
["Arabesque No 2", "G Major", "Debussy", 4, 4, "Romantic", [], "Two Arabesques"],
["Bells Through the Leaves", "", "Debussy", 5, 4, "Romantic", ["impressions"], ["Images Book 2", 1]],
["Clair De Lune", "Db Major", "Debussy", 6, 2, "Romantic", ["tender", "sleepy", "zen"], ["Suite Bergamasque", 3]],
["Danse Bohemienne", "b minor", "Debussy", 2, 5, "Romantic", [], ""],
["Doctor Gradus ad Parnassum", "C Major", "Debussy", 2, 5, "Romantic", [], ""],
["Evening in Granada", "f# minor", "Debussy", 6, 3, "Romantic", ["impressions"], ["Estampes", 2]],
["Gardens in the Rain", "e minor", "Debussy", 4, 3, "Romantic", [], ["Estampes", 3]],
["Goldfish", "F# Major", "Debussy", 4, 5, "Romantic", ["impressions"], ["Images Book 2", 3]],
["Golliwoggs Cakewalk", "Eb Major", "Debussy", 4, 5, "Romantic", [], ""],
["Hommage a Rameau", "", "Debussy", 6, 5, "Romantic", ["impressions"], ["Images Book 1", 2]],
["La Cathedrale Engloutie", "C Major", "Debussy", 7, 4, "Romantic", ["impressions"], ""],
["La Fille aux Cheveux de Lin", "Gb Major", "Debussy", 3, 5, "Romantic", ["impressions"], ""],
["Le vent dans la plaine", "", "Debussy", 3, 5, "Romantic", [], ""],
["Lisle Joyeuse", "A Major", "Debussy", 6, 2, "Romantic", ["impressions"], ""],
["Menuet", "a minor", "Debussy", 5, 4, "Romantic", [], ["Suite Bergamasque", 2]],
["Mouvement", "C Major", "Debussy", 4, 4, "Romantic", ["stamina"], ["Images Book 1", 3]],
["Nocturne L 82", "Db Major", "Debussy", 7, 5, "Romantic", ["impressions"], ""],
["Pagodas", "B Major", "Debussy", 6, 3, "Romantic", ["impressions"], ["Estampes", 1]],
["Prelude from Suite Bergamasque", "F Major", "Debussy", 5, 4, "Romantic", [], ["Suite Bergamasque", 1]],
["Prelude L 117 No 2", "", "Debussy", 5, 5, "Romantic", ["impressions"], ""],
["Prelude L 117 No 4", "", "Debussy", 5, 5, "Romantic", ["impressions"], ""],
["Prelude L 117 No 5", "", "Debussy", 4, 5, "Romantic", ["impressions"], ""],
["Passapied", "f# minor", "Debussy", 4, 5, "Romantic", [], ["Suite Bergamasque", 4]],
["Reflections in the Water", "Db Major", "Debussy", 5, 3,  "Romantic", ["sleepy", "impressions"], ["Images Book 1", 1]],
["Reverie", "F Major", "Debussy", 5, 4, "Romantic", [], ""],
["The Little Shepherd", "A Major", "Debussy", 3, 5, "Romantic", [], ""],
["Cello Concerto Op 104 Mvt 1", "b minor", "Dvorak", 16, 4, "Romantic", [], "Cello Concerto Op 104"],
["Cello Concerto Op 104 Mvt 2", "G Major", "Dvorak", 14, 5, "Romantic", ["uplifting"], "Cello Concerto Op 104"],
["Cello Concerto Op 104 Mvt 3", "b minor", "Dvorak", 14, 5, "Romantic", [], "Cello Concerto Op 104"],
["New World Symphony Mvt 1", "e minor", "Dvorak", 13, 5, "Romantic", [], "New World Symphony"],
["New World Symphony Mvt 2", "Db Major", "Dvorak", 13, 4, "Romantic", ["uplifting"], "New World Symphony"],
["New World Symphony Mvt 3", "e minor", "Dvorak", 9, 5, "Romantic", [], "New World Symphony"],
["New World Symphony Mvt 4", "e minor", "Dvorak", 13, 5, "Romantic", [], "New World Symphony"],
["Pavane Op 50", "f# minor", "Faure", 8, 4, "Romantic", [], ""],
["Sicilienne Op 80 No 4", "g minor", "Faure", 5, 4, "Romantic", ["tender"], ""],
["Nocturne H 24", "Eb Major", "Field", 4, 5, "Romantic", ["sleepy"], ""],
["Nocturne H 25", "c minor", "Field", 4, 5, "Romantic", ["sleepy"], ""],
["Nocturne H 37", "Bb Major", "Field", 4, 4, "Romantic", ["sleepy"], ""],
["Nocturne H 56", "Eb Major", "Field", 6, 4, "Romantic", ["sleepy"], ""],
["Harp Concerto Mvt 1", "Eb Major", "Gliere", 12, 5, "Contemporary", [], "Harp Concerto"],
["Harp Concerto Mvt 2", "Cb Major", "Gliere", 6, 5, "Contemporary", [], "Harp Concerto"],
["Harp Concerto Mvt 3", "Eb Major", "Gliere", 13, 4, "Contemporary", [], "Harp Concerto"],
["Horn Concerto Mvt 1", "Bb Major", "Gliere", 13, 4, "Contemporary", [], "Horn Concerto"],
["Horn Concerto Mvt 2", "Eb Major", "Gliere", 7, 4, "Contemporary", ["tender"], "Horn Concerto"],
["Horn Concerto Mvt 3", "Bb Major", "Gliere", 7, 4, "Contemporary", [], "Horn Concerto"],
["The Lark", "bb minor", "Glinka", 6, 3, "Romantic", ["sad"], ""],
["March of the Trolls Op 54 No 3", "d minor", "Grieg", 2, 3, "Romantic", ["stamina"], ""],
["Notturno Op 54 No 4", "a minor", "Grieg", 4, 4, "Romantic", [], ""],
["Peer Gynt Suite No 1", "E Major", "Grieg", 15, 3, "Romantic", [], "Peer Gynt Suite No 1"],
["Peer Gynt Suite No 2", "g minor", "Grieg", 17, 4, "Romantic", [], "Peer Gynt Suite No 2"],
["Piano Concerto Op 16 Mvt 1", "a minor", "Grieg", 15, 3, "Romantic", [], "Piano Concerto Op 16"],
["Piano Concerto Op 16 Mvt 2", "Db Major", "Grieg", 8, 3, "Romantic", ["uplifting", "tender", "sleepy"], "Piano Concerto Op 16"],
["Piano Concerto Op 16 Mvt 3", "a minor", "Grieg", 11, 3, "Romantic", ["stamina"], "Piano Concerto Op 16"],
["Piano Sonata No 7", "e minor", "Grieg", 19, 4, "Romantic", [], ""],
["Hallelujah", "D Major", "Handel", 5, 5, "Baroque", [], ""],
["Piano Concerto No 11 Mvt 1", "D Major", "Haydn", 9, 4, "Classical", [], "Piano Concerto No 11"],
["Piano Concerto No 11 Mvt 2", "A Major", "Haydn", 9, 4, "Classical", [], "Piano Concerto No 11"],
["Piano Concerto No 11 Mvt 3", "D Major", "Haydn", 5, 4, "Classical", ["stamina"], "Piano Concerto No 11"],
["Piano Sonata No 50", "D Major", "Haydn", 6, 4, "Classical", ["stamina"], ""],
["Symphony No 47 Mvt 3", "G Major", "Haydn", 3, 5, "Classical", ["troll"], ""],
["Waltz from Masquerade Suite", "a minor", "Khachaturian", 5, 4, "Contemporary", [], ""],
["Liebeslied", "a minor", "Kreisler", 4, 5, "Contemporary", ["sad"], ""],
["Andalucia", "D Major", "Lecuona", 3, 4, "Contemporary", [], ""],
["Danza Lucumi", "Db Major", "Lecuona", 3, 4, "Contemporary", [], ""],
["Malaguena", "c# minor", "Lecuona", 4, 4, "Contemporary", [], ""],
["Gargoyles", "", "Liebermann", 10, 4, "Contemporary", ["troll"], ""],
["Au bord dune source", "Ab Major", "Liszt", 4, 4, "Romantic", ["tender", "sleepy"], ["Years of Pilgrimage 1: Switzerland S 160", 4]],
["Au lac de Wallenstadt", "Ab Major", "Liszt", 4, 2, "Romantic", ["tender", "sleepy"], ["Years of Pilgrimage 1: Switzerland S 160", 2]],
["Ave Maria S 173 No 2", "Bb Major", "Liszt", 9, 5, "Romantic", ["tender", "sleepy"], ""],
["Ballade No 1 S 170", "Db Major", "Liszt", 8, 4, "Romantic", ["experimental"], ""],
["Ballade No 2 S 171", "b minor", "Liszt", 16, 4, "Romantic", ["experimental"], ""],
["Ballade Ukraine S 249 No 1", "b minor", "Liszt", 9, 5, "Romantic", [], ["Glanes de Woronince S 249", 1]],
["Benediction de Dieu dans la solitude S 173 No 3", "F# Major", "Liszt", 18, 1, "Romantic", ["legendary", "tender", "sleepy", "zen"], ""],
["Berceuse S 186 No 7", "F# Major", "Liszt", 4, 4, "Romantic", ["tender", "sleepy"], ""],
["Chapelle de Guillaume Tell", "C Major", "Liszt", 6, 5, "Romantic", [], ["Years of Pilgrimage 1: Switzerland S 160", 1]],
["Complainte S 249 No 3", "c# minor", "Liszt", 6, 5, "Romantic", [], ["Glanes de Woronince S 249", 3]],
["Consolation No 1", "E Major", "Liszt", 2, 4, "Romantic", ["tender", "sleepy"], "6 Consolations S 172"],
["Consolation No 2", "E Major", "Liszt", 4, 4, "Romantic", ["tender", "sleepy"], "6 Consolations S 172"],
["Consolation No 3", "Db Major", "Liszt", 6, 2, "Romantic", ["tender", "sleepy", "zen"], "6 Consolations S 172"],
["Consolation No 4", "Db Major", "Liszt", 4, 5, "Romantic", ["tender"], "6 Consolations S 172"],
["Consolation No 5", "E Major", "Liszt", 3, 4, "Romantic", ["tender", "sleepy"], "6 Consolations S 172"],
["Consolation No 6", "E Major", "Liszt", 3, 4, "Romantic", ["tender", "sleepy"], "6 Consolations S 172"],
["Eglogue", "Ab Major", "Liszt", 4, 3, "Romantic", ["tender", "sleepy"], ["Years of Pilgrimage 1: Switzerland S 160", 6]],
["Elegie S 168", "Ab Major", "Liszt", 8, 4, "Romantic", [], ""],
["Etude S 141 No 1", "g minor", "Liszt", 5, 4, "Romantic", [], ["Six Grand Paganini Etudes S 141", 1]],
["Etude S 141 No 2", "Eb Major", "Liszt", 6, 4, "Romantic", [], ["Six Grand Paganini Etudes S 141", 2]],
["Etude S 141 No 4", "E Major", "Liszt", 2, 4, "Romantic", [], ["Six Grand Paganini Etudes S 141", 4]],
["Etude S 141 No 5", "E Major", "Liszt", 3, 4, "Romantic", [], ["Six Grand Paganini Etudes S 141", 5]],
["Etude S 141 No 6", "a minor", "Liszt", 5, 4, "Romantic", [], ["Six Grand Paganini Etudes S 141", 6]],
["Galop de Bal S 220", "Bb Major", "Liszt", 1, 4, "Romantic", ["stamina"], ""],
["Gnomenreigen", "f# minor", "Liszt", 3, 4, "Romantic", [], ["2 Concert Etudes S 145", 2]],
["Grand Galop Chromatique S 219", "Eb Major", "Liszt", 4, 3, "Romantic", ["stamina"], ""],
["Hungarian Rhapsody S 244 No 2", "c# minor", "Liszt", 9, 2, "Romantic", ["dark"], ""],
["Il Lamento", "Ab Major", "Liszt", 10, 3, "Romantic", [], ["3 Concert Etudes S 144", 1]],
["La Campanella", "g# minor", "Liszt", 5, 3, "Romantic", [], ["Six Grand Paganini Etudes S 141", 3]],
["La Leggierezza", "f minor", "Liszt", 5, 2, "Romantic", ["dark"], ["3 Concert Etudes S 144", 2]],
["Le mal du pays", "e minor", "Liszt", 6, 5, "Romantic", [], ["Years of Pilgrimage 1: Switzerland S 160", 7]],
["Les cloches de Geneve", "B Major", "Liszt", 6, 5, "Romantic", [], ["Years of Pilgrimage 1: Switzerland S 160", 8]],
["Liebestraum No 1", "Ab Major", "Liszt", 8, 4, "Romantic", ["tender"], "Liebestraume S 541"],
["Liebestraum No 2", "Eb Major", "Liszt", 5, 4, "Romantic", [], "Liebestraume S 541"],
["Liebestraum No 3", "Ab Major", "Liszt", 5, 2, "Romantic", ["tender"], "Liebestraume S 541"],
["Melodies Polonaises S 249 No 2", "Ab Major", "Liszt", 5, 5, "Romantic", [], ["Glanes de Woronince S 249", 2]],
["Mephisto Waltz S 514 No 1", "A Major", "Liszt", 12, 3, "Romantic", ["experimental", "stamina"], ""],
["Orage", "c minor", "Liszt", 5, 5, "Romantic", ["dark"], ["Years of Pilgrimage 1: Switzerland S 160", 5]],
["Pastorale", "E Major", "Liszt", 2, 5, "Romantic", [], ["Years of Pilgrimage 1: Switzerland S 160", 3]],
["Piano Concerto No 1", "Eb Major", "Liszt", 19, 3, "Romantic", ["experimental"], "Piano Concerto No 1"],
["Piano Concerto No 2", "A Major", "Liszt", 23, 4, "Romantic", ["experimental"], "Piano Concerto No 2"],
["Rondo El Contrabandista S 252", "g minor", "Liszt", 12, 4, "Romantic", ["experimental", "stamina"], ""],
["Russian Galop S 478", "Bb Major", "Liszt", 3, 4, "Romantic", ["stamina"], ""],
["Seven Brilliant Variations on a Theme of Rossini S 149", "A Major", "Liszt", 10, 4, "Romantic", [], ""],
["Sonata S 178", "b minor", "Liszt", 31, 2, "Romantic", ["dark", "experimental", "legendary"], "Sonata S 178"],
["Spanish Fantasy S 253", "D Major", "Liszt", 13, 4, "Romantic", [], ""],
["The Fountains of the Villa dEste S 163 No 4", "F# Major", "Liszt", 8, 5, "Romantic", ["tender", "sleepy"], ""],
["The Nightingale S 250", "c# minor", "Liszt", 4, 4, "Romantic", [], ""],
["Transcendental Etude S 139 No 3", "F Major", "Liszt", 5, 4, "Romantic", ["sleepy"], ""],
["Transcendental Etude S 139 No 8", "c minor", "Liszt", 6, 5, "Romantic", [], ""],
["Un Sospiro", "Db Major", "Liszt", 6, 2, "Romantic", ["tender", "sleepy", "zen"], ["3 Concert Etudes S 144", 3]],
["Waldesrauschen", "Db Major", "Liszt", 5, 2, "Romantic", ["tender", "sleepy", "zen"], ["2 Concert Etudes S 145", 1]],
["Intermezzo from Cavalleria Rusticana", "F Major", "Mascagni", 4, 4, "Romantic", [], ""],
["Meditation from Thais", "D Major", "Massenet", 5, 4, "Romantic", ["tender"], ""],
["A Midsummer Nights Dream Overture", "E Major", "Mendelssohn", 13, 4, "Romantic", [], ["A Midsummer Nights Dream", 1]],
["Caprice Op 5", "f# minor", "Mendelssohn", 7, 4, "Romantic", [], ""],
["Caprice Op 33 No 1", "a minor", "Mendelssohn", 9, 4, "Romantic", [], "Three Caprices Op 33"],
["Caprice Op 33 No 2", "E Major", "Mendelssohn", 9, 4, "Romantic", [], "Three Caprices Op 33"],
["Caprice Op 33 No 3", "bb minor", "Mendelssohn", 7, 4, "Romantic", [], "Three Caprices Op 33"],
["Dance of the Clowns", "B Major", "Mendelssohn", 2, 4, "Romantic", [], ["A Midsummer Nights Dream", 6]],
["Etude WoO 1", "f minor", "Mendelssohn", 2, 5, "Romantic", [], ""],
["Fantasia Op 15", "E Major", "Mendelssohn", 9, 4, "Romantic", [], ""],
["Intermezzo", "a minor", "Mendelssohn", 5, 4, "Romantic", [], ["A Midsummer Nights Dream", 3]],
["Nocturne", "E Major", "Mendelssohn", 6, 4, "Romantic", ["uplifting"], ["A Midsummer Nights Dream", 4]],
["Piano Concerto No 1 Mvt 1", "g minor", "Mendelssohn", 7, 3, "Romantic", ["dark", "stamina"], "Piano Concerto No 1"],
["Piano Concerto No 1 Mvt 2", "E Major", "Mendelssohn", 7, 3, "Romantic", ["tender"], "Piano Concerto No 1"],
["Piano Concerto No 1 Mvt 3", "G Major", "Mendelssohn", 6, 3, "Romantic", ["stamina"], "Piano Concerto No 1"],
["Piano Concerto No 2 Mvt 1", "d minor", "Mendelssohn", 11, 4, "Romantic", ["dark"], "Piano Concerto No 2"],
["Piano Concerto No 2 Mvt 2", "Bb Major", "Mendelssohn", 8, 3, "Romantic", ["tender", "sleepy", "uplifting"], "Piano Concerto No 2"],
["Piano Concerto No 2 Mvt 3", "D Major", "Mendelssohn", 8, 4, "Romantic", [], "Piano Concerto No 2"],
["Rondo Capriccioso Op 14", "e minor", "Mendelssohn", 7, 3, "Romantic", [], ""],
["Scherzo", "g minor", "Mendelssohn", 5, 4, "Romantic", [], ["A Midsummer Nights Dream", 2]],
["Scherzo a Capriccio", "f# minor", "Mendelssohn", 7, 5, "Romantic", [], ""],
["Songs Without Words Op 19 No 1", "E Major", "Mendelssohn", 4, 5, "Romantic", ["tender"], ""],
["Songs Without Words Op 19 No 6", "g minor", "Mendelssohn", 2, 5, "Romantic", ["sad"], ""],
["Songs Without Words Op 30 No 6", "f# minor", "Mendelssohn", 3, 5, "Romantic", ["sad"], ""],
["Songs Without Words Op 38 No 2", "c minor", "Mendelssohn", 2, 5, "Romantic", [], ""],
["Symphony No 4 Mvt 1", "A Major", "Mendelssohn", 11, 3, "Romantic", ["stamina"], ""],
["The Hebrides Overture", "b minor", "Mendelssohn", 11, 4, "Romantic", [], ""],
["Violin Concerto Mvt 1", "e minor", "Mendelssohn", 13, 5, "Romantic", ["sad"], "Violin Concerto"],
["Violin Concerto Mvt 2", "C Major", "Mendelssohn", 9, 5, "Romantic", ["tender"], "Violin Concerto"],
["Violin Concerto Mvt 3", "E Major", "Mendelssohn", 7, 5, "Romantic", [], "Violin Concerto"],
["Wedding March", "C Major", "Mendelssohn", 5, 4, "Romantic", [], ["A Midsummer Nights Dream", 5]],
["Piano Concerto Op 59 Mvt 1", "E Major", "Moszkowski", 13, 4, "Romantic", [], "Piano Concerto Op 59"],
["Piano Concerto Op 59 Mvt 2", "c# minor", "Moszkowski", 9, 4, "Romantic", ["dark"], "Piano Concerto Op 59"],
["Piano Concerto Op 59 Mvt 3", "c# minor", "Moszkowski", 8, 4, "Romantic", ["stamina"], "Piano Concerto Op 59"],
["Piano Concerto Op 59 Mvt 4", "E Major", "Moszkowski", 10, 4, "Romantic", ["stamina"], "Piano Concerto Op 59"],
["12 Variations Ah vous diraisje maman", "C Major", "Mozart", 9, 4, "Classical", [], ""],
["Clarinet Concerto Mvt 1", "A Major", "Mozart", 13, 3, "Classical", [], "Clarinet Concerto"],
["Clarinet Concerto Mvt 2", "D Major", "Mozart", 8, 3, "Classical", ["uplifting"], "Clarinet Concerto"],
["Clarinet Concerto Mvt 3", "A Major", "Mozart", 9, 4, "Classical", [], "Clarinet Concerto"],
["Eine Kleine Nachtmusik", "G Major", "Mozart", 6, 5, "Classical", [], ""],
["Fantasia K 397", "d minor", "Mozart", 6, 4, "Classical", ["sad"], ""],
["Lacrimosa", "d minor", "Mozart", 4, 5, "Classical", ["sad"], ""],
["Piano Concerto No 21 Mvt 1", "C Major", "Mozart", 14, 4, "Classical", [], "Piano Concerto No 21"],
["Piano Concerto No 21 Mvt 2", "F Major", "Mozart", 7, 4, "Classical", ["sleepy"], "Piano Concerto No 21"],
["Piano Concerto No 21 Mvt 3", "C Major", "Mozart", 7, 4, "Classical", ["stamina"], "Piano Concerto No 21"],
["Piano Concerto No 23 Mvt 1", "A Major", "Mozart", 12, 3, "Classical", [], "Piano Concerto No 23"],
["Piano Concerto No 23 Mvt 2", "f# minor", "Mozart", 8, 3, "Classical", ["sad"], "Piano Concerto No 23"],
["Piano Concerto No 23 Mvt 3", "A Major", "Mozart", 9, 3, "Classical", ["stamina"], "Piano Concerto No 23"],
["Symphony No 40 Mvt 1", "g minor", "Mozart", 6, 5, "Classical", [], ""],
["Symphony No 40 Mvt 4", "g minor", "Mozart", 5, 5, "Classical", ["stamina"], ""],
["Symphony No 41 Mvt 1", "C Major", "Mozart", 8, 5, "Classical", ["stamina"], ""],
["Symphony No 41 Mvt 4", "C Major", "Mozart", 7, 5, "Classical", ["stamina"], ""],
["Night on Bald Mountain", "d minor", "Mussorgsky", 10, 4, "Romantic", ["stamina"], ""],
["Une Larme", "g minor", "Mussorgsky", 5, 5, "Romantic", [], ""],
["Galop Infernal", "D Major", "Offenbach", 6, 4, "Romantic", [], ""],
["Caprice 24", "a minor", "Paganini", 5, 4, "Romantic", [], ""],
["La Campanella", "b minor", "Paganini", 5, 5, "Romantic", [], ""],
["Improvisation No 7", "C Major", "Poulenc", 3, 5, "Contemporary", [], ""],
["Improvisation No 15", "c minor", "Poulenc", 4, 4, "Contemporary", ["tender"], ""],
["Dance of the Knights", "e minor", "Prokofiev", 6, 5, "Contemporary", ["dark", "troll"], ""],
["Sonata No 2", "d minor", "Prokofiev", 19, 3, "Contemporary", ["troll"], ""],
["Musettas Waltz", "E Major", "Puccini", 4, 4, "Romantic", [], ""],
["Barcarolle", "g minor", "Rachmaninoff", 8, 4, "Romantic", ["sad", "tender"], ""],
["Elegie Op 3 No 1", "eb minor", "Rachmaninoff", 6, 4, "Romantic", ["sleepy, impressions"], ["Morceaux de Fantaisie Op 3", 1]],
["Etude-Tableaux Op 33 No 1", "f minor", "Rachmaninoff", 3, 5, "Contemporary", [], "8 Etude-Tableaux Op 33"],
["Etude-Tableaux Op 33 No 2", "C Major", "Rachmaninoff", 3, 5, "Contemporary", [], "8 Etude-Tableaux Op 33"],
["Etude-Tableaux Op 33 No 3", "c minor", "Rachmaninoff", 6, 5, "Contemporary", [], "8 Etude-Tableaux Op 33"],
["Etude-Tableaux Op 33 No 4", "d minor", "Rachmaninoff", 4, 5, "Contemporary", ["impressions"], "8 Etude-Tableaux Op 33"],
["Etude-Tableaux Op 33 No 5", "eb minor", "Rachmaninoff", 2, 5, "Contemporary", ["impressions"], "8 Etude-Tableaux Op 33"],
["Etude-Tableaux Op 33 No 6", "Eb Major", "Rachmaninoff", 2, 2, "Contemporary", ["stamina"], "8 Etude-Tableaux Op 33"],
["Etude-Tableaux Op 33 No 7", "g minor", "Rachmaninoff", 4, 4, "Contemporary", [], "8 Etude-Tableaux Op 33"],
["Etude-Tableaux Op 33 No 8", "c# minor", "Rachmaninoff", 3, 5, "Contemporary", [], "8 Etude-Tableaux Op 33"],
["Etude-Tableaux Op 39 No 1", "c minor", "Rachmaninoff", 3, 4, "Contemporary", ["impressions"], ""],
["Etude-Tableaux Op 39 No 2", "a minor", "Rachmaninoff", 7, 3, "Contemporary", ["impressions"], ""],
["Etude-Tableaux Op 39 No 3", "f# minor", "Rachmaninoff", 3, 5, "Contemporary", ["impressions"], ""],
["Etude-Tableaux Op 39 No 4", "b minor", "Rachmaninoff", 4, 5, "Contemporary", [], ""],
["Etude-Tableaux Op 39 No 5", "eb minor", "Rachmaninoff", 6, 5, "Contemporary", ["dark"], ""],
["Etude-Tableaux Op 39 No 8", "d minor", "Rachmaninoff", 4, 5, "Contemporary", ["impressions"], ""],
["Etude-Tableaux Op 39 No 9", "D Major", "Rachmaninoff", 4, 5, "Contemporary", ["impressions"], ""],
["How Fair This Spot Op 21 No 7", "A Major", "Rachmaninoff", 3, 4, "Romantic", ["tender"], ""],
["Introduction Op 17 No 1", "C Major", "Rachmaninoff", 4, 4, "Romantic", [], ["Suite No 2", 1]],
["Italian Polka", "eb minor", "Rachmaninoff", 4, 4, "Romantic", ["dark"], ""],
["Lilacs Op 21 No 5", "Ab Major", "Rachmaninoff", 3, 1, "Romantic", ["sleepy", "impressions"], ""],
["Melody Op 3 No 3", "E Major", "Rachmaninoff", 5, 4, "Romantic", ["sleepy, impressions"],  ["Morceaux de Fantaisie Op 3", 3]],
["Moments Musicaux Op 16 No 1", "bb minor", "Rachmaninoff", 7, 4, "Romantic", ["impressions"], ""],
["Moments Musicaux Op 16 No 4", "e minor", "Rachmaninoff", 4, 4, "Romantic", [], ""],
["Moments Musicaux Op 16 No 5", "Db Major", "Rachmaninoff", 4, 4, "Romantic", ["sleepy, impressions"], ""],
["Moments Musicaux Op 16 No 6", "C Major", "Rachmaninoff", 5, 5, "Romantic", [], ""],
["Morceaux de Salon Op 10 No 2", "A Major", "Rachmaninoff", 4, 4, "Contemporary", [], ""],
["Morceaux de Salon Op 10 No 5", "G Major", "Rachmaninoff", 4, 4, "Contemporary", [], ""],
["Piano Concerto No 1 Mvt 1", "f# minor", "Rachmaninoff", 13, 4, "Romantic", ["legendary"], "Piano Concerto No 1"],
["Piano Concerto No 1 Mvt 2", "D Major", "Rachmaninoff", 7, 4, "Romantic", [], "Piano Concerto No 1"],
["Piano Concerto No 1 Mvt 3", "f# minor", "Rachmaninoff", 8, 4, "Romantic", [], "Piano Concerto No 1"],
["Piano Concerto No 2 Mvt 1", "c minor", "Rachmaninoff", 12, 1, "Romantic", ["dark", "legendary"], "Piano Concerto No 2"],
["Piano Concerto No 2 Mvt 2", "E Major", "Rachmaninoff", 13, 2, "Romantic", ["uplifting", "legendary"], "Piano Concerto No 2"],
["Piano Concerto No 2 Mvt 3", "c minor", "Rachmaninoff", 12, 3, "Romantic", [], "Piano Concerto No 2"],
["Piano Concerto No 3 Mvt 1", "d minor", "Rachmaninoff", 17, 3, "Romantic", [], "Piano Concerto No 3"],
["Piano Concerto No 3 Mvt 2", "d minor", "Rachmaninoff", 12, 4, "Romantic", [], "Piano Concerto No 3"],
["Piano Concerto No 3 Mvt 3", "d minor", "Rachmaninoff", 15, 4, "Romantic", ["stamina"], "Piano Concerto No 3"],
["Piano Sonata No 1", "d minor", "Rachmaninoff", 36, 3, "Contemporary", ["legendary"], "Piano Sonatas"],
["Piano Sonata No 2", "bb minor", "Rachmaninoff", 23, 2, "Contemporary", ["legendary", "dark", "experimental"], "Piano Sonatas"],
["Polichinelle Op 3 No 4", "f# minor", "Rachmaninoff", 4, 4, "Romantic", ["impressions"], ["Morceaux de Fantaisie Op 3", 4]],
["Prelude Op 3 No 2", "c# minor", "Rachmaninoff", 4, 3, "Romantic", ["dark"],  ["Morceaux de Fantaisie Op 3", 2]],
["Prelude Op 23 No 5", "g minor", "Rachmaninoff", 4, 4, "Romantic", ["stamina"], ""],
["Prelude Op 23 No 7", "c minor", "Rachmaninoff", 4, 5, "Romantic", ["impressions"], ""],
["Prelude Op 32 No 5", "G Major", "Rachmaninoff", 4, 2, "Romantic", ["uplifting", "sleepy, impressions"], ""],
["Prelude Op 32 No 12", "g# minor", "Rachmaninoff", 3, 4, "Romantic", [], ""],
["Rhapsody on a Theme by Paganini", "a minor", "Rachmaninoff", 25, 3, "Contemporary", [], ""],
["Romance Op 17 No 3", "Ab Major", "Rachmaninoff", 8, 4, "Romantic", ["tender", "uplifting"], ["Suite No 2", 3]],
["Serenade Op 3 No 5", "bb minor", "Rachmaninoff", 4, 4, "Romantic", [], ["Morceaux de Fantaisie Op 3", 5]],
["Symphonic Dance Op 45 No 1", "c minor", "Rachmaninoff", 12, 5, "Romantic", [], ""],
["Symphony No 2 Mvt 1", "e minor", "Rachmaninoff", 21, 1, "Romantic", ["legendary"], "Symphony No 2"],
["Symphony No 2 Mvt 2", "a minor", "Rachmaninoff", 11, 1, "Romantic", ["legendary", "stamina"], "Symphony No 2"],
["Symphony No 2 Mvt 3", "A Major", "Rachmaninoff", 15, 1, "Romantic", ["legendary", "uplifting"], "Symphony No 2"],
["Symphony No 2 Mvt 4", "E Major", "Rachmaninoff", 15, 1, "Romantic", ["legendary", "stamina"], "Symphony No 2"],
["Tarantelle Op 17 No 4", "c minor", "Rachmaninoff", 6, 4, "Romantic", [], ["Suite No 2", 4]],
["Variations on a Theme by Chopin", "c minor", "Rachmaninoff", 27, 4, "Romantic", [], ""],
["Waltz Op 17 No 2", "G Major", "Rachmaninoff", 6, 4, "Romantic", [], ["Suite No 2", 2]],
["Alborada del Gracioso", "", "Ravel", 7, 4, "Contemporary", [], ["Miroirs", 4]],
["Bolero", "C Major", "Ravel", 15, 5, "Contemporary", ["troll"], ""],
["La Vallee des Cloches", "", "Ravel", 6, 4, "Contemporary", ["impressions"], ["Miroirs", 5]],
["Le Gibet", "eb minor", "Ravel", 7, 4, "Contemporary", ["impressions"], ["Gaspard de la Nuit", 2]],
["Noctuelles", "", "Ravel", 5, 4, "Contemporary", ["impressions"], ["Miroirs", 1]],
["Oiseaux Tristes", "", "Ravel", 4, 5, "Contemporary", ["impressions"], ["Miroirs", 2]],
["Ondine", "C# Major", "Ravel", 7, 3, "Contemporary", ["impressions"], ["Gaspard de la Nuit", 1]],
["Pavane for Dead Princess", "G Major", "Ravel", 7, 5, "Contemporary", [], ""],
["Piano Concerto Mvt 1", "G Major", "Ravel", 9, 5, "Contemporary", ["troll"], "Piano Concerto"],
["Piano Concerto Mvt 2", "E Major", "Ravel", 10, 5, "Contemporary", ["troll"], "Piano Concerto"],
["Piano Concerto Mvt 3", "G Major", "Ravel", 4, 5, "Contemporary", ["troll"], "Piano Concerto"],
["Scarbo", "B Major", "Ravel", 9, 4, "Contemporary", ["impressions"], ["Gaspard de la Nuit", 3]],
["Une Barque sur la Ocean", "A Major", "Ravel", 7, 4, "Contemporary", ["impressions"], ["Miroirs", 3]],
["Intermezzo Serenata", "E Major", "Respighi", 3, 3, "Romantic", ["tender", "sleepy"], ""],
["Valse Caressante", "Eb Major", "Respighi", 4, 3, "Romantic", ["tender", "sleepy"], ""],
["Capriccio Espagnol", "A Major", "RimskyKorsakov", 16, 2, "Romantic", ["stamina"], "Capriccio Espagnol"],
["Flight of the Bumblebee", "a minor", "RimskyKorsakov", 1, 5, "Romantic", ["stamina", "troll"], ""],
["Procession of Nobles", "Eb Major", "RimskyKorsakov", 5, 5, "Romantic", [], ""],
["Barber of Seville", "E Major", "Rossini", 8, 4, "Romantic", [], ""],
["William Tell Overture Finale", "E Major", "Rossini", 4, 4, "Romantic", ["stamina"], ""],
["Aquarium", "a minor", "SaintSaens", 3, 4, "Romantic", ["sleepy, impressions"], ["Carnival of the Animals", 7]],
["Aviary", "F Major", "SaintSaens", 2, 4, "Romantic", ["uplifting", "sleepy"], ["Carnival of the Animals", 10]],
["Bacchanale from Samson and Delilah", "d minor", "SaintSaens", 8, 4, "Romantic", [], ""],
["Danse Macabre", "g minor", "SaintSaens", 8, 3, "Romantic", ["dark"], ""],
["Donkeys", "a minor", "SaintSaens", 1, 5, "Romantic", ["troll"], ["Carnival of the Animals", 8]],
["Fast Animals", "c minor", "SaintSaens", 1, 5, "Romantic", ["stamina"], ["Carnival of the Animals", 3]],
["Finale", "C Major", "SaintSaens", 2, 3, "Romantic", ["stamina"], ["Carnival of the Animals", 14]],
["Fossils", "G Major", "SaintSaens", 2, 5, "Romantic", [], ["Carnival of the Animals", 12]],
["Hens and Roosters", "", "SaintSaens", 1, 5, "Romantic", [], ["Carnival of the Animals", 2]],
["Introduction and Rondo Capriccioso Op 28", "a minor", "SaintSaens", 9, 5, "Romantic", ["sad"], ""],
["Kangaroos", "Bb Major", "SaintSaens", 2, 5, "Romantic", ["sleepy"], ["Carnival of the Animals", 6]],
["Pianists", "C Major", "SaintSaens", 2, 5, "Romantic", ["troll"], ["Carnival of the Animals", 11]],
["Piano Concerto No 2 Mvt 1", "g minor", "SaintSaens", 14, 3, "Romantic", [], "Piano Concerto No 2"],
["Piano Concerto No 2 Mvt 2", "Eb Major", "SaintSaens", 7, 3, "Romantic", [], "Piano Concerto No 2"],
["Piano Concerto No 2 Mvt 3", "g minor", "SaintSaens", 7, 3, "Romantic", ["dark", "stamina"], "Piano Concerto No 2"],
["Piano Concerto No 4 Mvt 1", "c minor", "SaintSaens", 13, 3, "Romantic", [], "Piano Concerto No 4"],
["Piano Concerto No 4 Mvt 2", "C Major", "SaintSaens", 14, 4, "Romantic", [], "Piano Concerto No 4"],
["Piano Concerto No 5 Mvt 1", "F Major", "SaintSaens", 10, 2, "Romantic", [], "Piano Concerto No 5"],
["Piano Concerto No 5 Mvt 2", "d minor", "SaintSaens", 11, 4, "Romantic", [], "Piano Concerto No 5"],
["Piano Concerto No 5 Mvt 3", "F Major", "SaintSaens", 6, 2, "Romantic", ["stamina"], "Piano Concerto No 5"],
["Romance Op 67", "E Major", "SaintSaens", 8, 4, "Romantic", ["sleepy"], ""],
["The Cuckoo", "c# minor", "SaintSaens", 3, 5, "Romantic", ["impressions"], ["Carnival of the Animals", 9]],
["The Elephant", "Eb Major", "SaintSaens", 2, 5, "Romantic", [], ["Carnival of the Animals", 5]],
["The Lion", "G Major", "SaintSaens", 3, 5, "Romantic", [], ["Carnival of the Animals", 1]],
["The Swan", "G Major", "SaintSaens", 3, 3, "Romantic", ["tender", "sleepy"], ["Carnival of the Animals", 13]],
["Turtles", "Bb Major", "SaintSaens", 2, 4, "Romantic", ["sleepy"], ["Carnival of the Animals", 4]],
["Violin Concerto No 3 Mvt 1", "b minor", "SaintSaens", 10, 5, "Romantic", [], ""],
["Gnossienne No 1", "f minor", "Satie", 4, 4, "Romantic", ["tender", "sleepy"], ""],
["Gymnopedie No 1", "D Major", "Satie", 4, 5, "Romantic", ["troll"], ""],
["Je te veux", "C Major", "Satie", 5, 4, "Romantic", [], ""],
["Humoresque", "Db Major", "Schedrin", 2, 5, "Contemporary", ["troll"], ""],
["Ave Maria", "Bb Major", "Schubert", 5, 3, "Romantic", ["tender", "sleepy"], ""],
["Erlkonig", "g minor", "Schubert", 5, 4, "Romantic", ["dark"], ""],
["Impromptu Op 90 No 1", "c minor", "Schubert", 10, 4, "Romantic", ["sad"], "Four Impromptus Op 90"],
["Impromptu Op 90 No 2", "Eb Major", "Schubert", 5, 5, "Romantic", [], "Four Impromptus Op 90"],
["Impromptu Op 90 No 3", "Gb Major", "Schubert", 7, 5, "Romantic", ["sleepy"], "Four Impromptus Op 90"],
["Impromptu Op 90 No 4", "Ab Major", "Schubert", 7, 5, "Romantic", [], "Four Impromptus Op 90"],
["Impromptu Op 142 No 1", "f minor", "Schubert", 12, 5, "Romantic", [], "Four Impromptus Op 142"],
["Impromptu Op 142 No 2", "Ab Major", "Schubert", 8, 5, "Romantic", [], "Four Impromptus Op 142"],
["Impromptu Op 142 No 3", "Bb Major", "Schubert", 12, 4, "Romantic", ["tender", "sleepy"], "Four Impromptus Op 142"],
["Impromptu Op 142 No 4", "f minor", "Schubert", 6, 5, "Romantic", [], "Four Impromptus Op 142"],
["Serenade", "d minor", "Schubert", 4, 5, "Romantic", ["sad"], ""],
["Symphony No 5 Mvt 1", "Bb Major", "Schubert", 8, 4, "Romantic", [], "Symphony No 5"],
["Symphony No 5 Mvt 2", "Eb Major", "Schubert", 10, 4, "Romantic", [], "Symphony No 5"],
["Symphony No 5 Mvt 3", "g minor", "Schubert", 6, 4, "Romantic", [], "Symphony No 5"],
["Symphony No 5 Mvt 4", "Bb Major", "Schubert", 7, 4, "Romantic", [], "Symphony No 5"],
["Symphony No 8 Mvt 1", "b minor", "Schubert", 14, 3, "Romantic", [], "Symphony No 8"],
["Symphony No 8 Mvt 2", "E Major", "Schubert", 13, 4, "Romantic", [], "Symphony No 8"],
["Wanderer Fantasy Op 15", "C Major", "Schubert", 21, 4, "Romantic", ["legendary"], ""],
["Aufschwung Op 12 No 2", "f minor", "Schumann", 4, 5, "Romantic", [], ""],
["Dreaming Op 15 No 7", "F Major", "Schumann", 3, 5, "Romantic", ["sleepy"], ""],
["Des Abends Op 12 No 1", "Db Major", "Schumann", 4, 5, "Romantic", ["sleepy"], ""],
["Eintritt", "Bb Major", "Schumann", 2, 5, "Romantic", [], ""],
["In der Nacht Op 12 No 5", "f minor", "Schumann", 4, 5, "Romantic", ["dark"], ""],
["Of Foreign Lands and Peoples", "G Major", "Schumann", 2, 5, "Romantic", ["sleepy"], ""],
["Piano Concerto Op 54 Mvt 1", "a minor", "Schumann", 13, 4, "Romantic", [], "Piano Concerto Op 54"],
["Piano Concerto Op 54 Mvt 2", "F Major", "Schumann", 5, 4, "Romantic", [], "Piano Concerto Op 54"],
["Piano Concerto Op 54 Mvt 3", "A Major", "Schumann", 11, 4, "Romantic", [], "Piano Concerto Op 54"],
["Sonata No 1 Op 11", "f# minor", "Schumann", 30, 4, "Romantic", [], ""],
["Sonata No 2 Op 22", "g minor", "Schumann", 18, 3, "Romantic", ["dark", "legendary"], ""],
["Widmung", "Ab Major", "Schumann", 4, 4, "Romantic", ["tender"], ""],
["Etude Op 8 No 12", "d# minor", "Scriabin", 3, 4, "Romantic", ["dark"], ""],
["Etude Op 42 No 5", "c# minor", "Scriabin", 3, 4, "Romantic", ["dark", "impressions"], ""],
["Fantasy Op 28", "b minor", "Scriabin", 10, 4, "Romantic", ["dark"], ""],
["Prelude Op 11 No 1", "C Major", "Scriabin", 1, 5, "Romantic", ["impressions"], ""],
["Prelude Op 11 No 8", "f# minor", "Scriabin", 2, 5, "Romantic", ["dark"], ""],
["Prelude Op 11 No 10", "c# minor", "Scriabin", 2, 5, "Romantic", [], ""],
["Sonata No 2", "g# minor", "Scriabin", 15, 3, "Romantic", ["experimental", "legendary"], ""],
["Piano Concerto No 2 Mvt 1", "F Major", "Shostakovich", 8, 3, "Contemporary", ["stamina"], "Piano Concerto No 2"],
["Piano Concerto No 2 Mvt 2", "c minor", "Shostakovich", 7, 2, "Contemporary", ["tender", "sleepy", "impressions"], "Piano Concerto No 2"],
["Piano Concerto No 2 Mvt 3", "F Major", "Shostakovich", 6, 3, "Contemporary", ["stamina"], "Piano Concerto No 2"],
["Waltz No 2", "c minor", "Shostakovich", 4, 5, "Contemporary", [], ""],
["Karelia Suite", "Eb Major", "Sibelius", 17, 2, "Romantic", [], "Karelia Suite"],
["The Spruce", "D Major", "Sibelius", 4, 4, "Romantic", [], ""],
["La Moldau", "e minor", "Smetana", 14, 4, "Romantic", [], ""],
["Blue Danube", "D Major", "Strauss", 10, 3, "Romantic", ["uplifting"], ""],
["Fledermaus Overture", "A Major", "Strauss", 9, 4, "Romantic", [], ""],
["Voices of Spring", "Bb Major", "Strauss", 6, 4, "Romantic", [], ""],
["Infernal Dance", "a minor", "Stravinsky", 6, 5, "Contemporary", ["troll"], ""],
["April Snowdrop", "Bb Major", "Tchaikovsky", 3, 4, "Romantic", [], ["The Seasons", 4]],
["Dance of the Little Swans", "f# minor", "Tchaikovsky", 2, 5, "Romantic", [], ""],
["Dance of the Suger Plum Fairy", "e minor", "Tchaikovsky", 2, 5, "Romantic", [], ""],
["December Christmas", "Ab Major", "Tchaikovsky", 5, 5, "Romantic", [], ["The Seasons", 7]],
["February The Carnival", "D Major", "Tchaikovsky", 3, 5, "Romantic", [], ["The Seasons", 2]],
["March Song of the Lark", "g minor", "Tchaikovsky", 3, 5, "Romantic", ["sad", "tender"], ["The Seasons", 3]],
["Marche", "G Major", "Tchaikovsky", 3, 5, "Romantic", ["stamina"], ""],
["Marche Slave", "bb minor", "Tchaikovsky", 10, 5, "Romantic", [], ""],
["January At the Fireside", "A Major", "Tchaikovsky", 6, 5, "Romantic", [], ["The Seasons", 1]],
["June Barcarolle", "g minor", "Tchaikovsky", 5, 5, "Romantic", ["sad", "tender"], ["The Seasons", 5]],
["November On the Troika", "E Major", "Tchaikovsky", 4, 5, "Romantic", [], ["The Seasons", 6]],
["Pas de Deux", "G Major", "Tchaikovsky", 6, 5, "Romantic", [], ""],
["Piano Concerto No 1 Mvt 1", "bb minor", "Tchaikovsky", 22, 4, "Romantic", [], "Piano Concerto No 1"],
["Piano Concerto No 1 Mvt 2", "Db Major", "Tchaikovsky", 8, 3, "Romantic", ["tender", "uplifting"], "Piano Concerto No 1"],
["Piano Concerto No 1 Mvt 3", "bb minor", "Tchaikovsky", 7, 4, "Romantic", ["dark", "stamina"], "Piano Concerto No 1"],
["Sleeping Beauty Waltz", "Bb Major", "Tchaikovsky", 5, 5, "Romantic", [], ""],
["Swan Lake Waltz", "A Major", "Tchaikovsky", 8, 5, "Romantic", [], ""],
["Swan Lake Theme", "b minor", "Tchaikovsky", 3, 5, "Romantic", [], ""],
["Trepak", "G Major", "Tchaikovsky", 2, 5, "Romantic", ["stamina"], ""],
["Valse Sentimentale Op 51 No 6", "f minor", "Tchaikovsky", 5, 5, "Romantic", ["sad"], ""],
["Waltz of the Flowers", "D Major", "Tchaikovsky", 7, 5, "Romantic", [], ""],
["Spring", "b minor", "Vivaldi", 4, 5, "Baroque", [], ""],
["Ride of the Valkyries", "b minor", "Wagner", 5, 4, "Romantic", [], ""]];

/*
The metadata of each piece is stored in a list with the given format.
[piece name, key, composer, length (in minutes), rating (best = 1, worst = 5), era, playlists it belongs in, albums it belongs in]
albums it belongs in can either be a string or a list. if a list, stores [album name, index]. otherwise, indices are assumed to follow the default order given.
*/

//Build album map

const albumMap = new Map();

for (let i = 0; i < pieces.length; i++) {
    const data = pieces[i];
    const albumInfo = data[data.length - 1];

    if (albumInfo === "") {
        continue;
    }

    const composer = data[2];
    const albumName = typeof albumInfo === "string" ? `${composer}: ${albumInfo}` : `${composer}: ${albumInfo[0]}`;

    if (!albumMap.has(albumName)) {
        albumMap.set(albumName, []);
    }

    const albumList = albumMap.get(albumName);

    if (typeof albumInfo === "string") {
        albumList.push([data[0], composer, data[3], i]);
    } 
    else {
        const idx = albumInfo[1] - 1;
        albumList[idx] = [data[0], composer, data[3], i];
    }
}

const albumList = Array.from(albumMap.keys()).sort();